
import { COUNTRY_ALIASES } from './data/aliases';
import { Country, Game } from './types';
export { TERRITORIES } from './data/territories';
export { DE_FACTO_COUNTRIES } from './data/deFacto';

const RAW_COUNTRIES: Country[] = [
  // --- A ---
  { id: '1', name: 'Afghanistan', capital: 'Kabul', population: '41.1M', region: 'Asia', flag: '🇦🇫', lat: 34.5553, lng: 69.2075, description: 'A landlocked country at the crossroads of Central and South Asia, known for its rugged mountains and rich history.', area: '652K', currency: 'Afghan afghani', languages: ['Pashto', 'Dari'], borders: ['Iran', 'Pakistan', 'Turkmenistan', 'Uzbekistan', 'Tajikistan', 'China'], gdp: '$14.5B', timeZone: 'UTC+4:30', callingCode: '+93', driveSide: 'Right' },
  { id: '2', name: 'Albania', capital: 'Tirana', population: '2.8M', region: 'Europe', flag: '🇦🇱', lat: 41.3275, lng: 19.8187, description: 'A country in Southeastern Europe on the Adriatic and Ionian Sea, featuring ancient castles and the Albanian Alps.', area: '28.7K', currency: 'Albanian lek', languages: ['Albanian'], borders: ['Montenegro', 'Kosovo', 'North Macedonia', 'Greece'], gdp: '$18.3B', timeZone: 'UTC+1', callingCode: '+355', driveSide: 'Right' },
  { id: '3', name: 'Algeria', capital: 'Algiers', population: '44.9M', region: 'Africa', flag: '🇩🇿', lat: 36.7538, lng: 3.0588, description: 'The largest country in Africa, featuring a Mediterranean coastline and the vast interior of the Sahara desert.', area: '2.38M', currency: 'Algerian dinar', languages: ['Arabic', 'Berber'], borders: ['Tunisia', 'Libya', 'Niger', 'Mali', 'Mauritania', 'Morocco'], gdp: '$191.9B', timeZone: 'UTC+1', callingCode: '+213', driveSide: 'Right' },
  { id: '4', name: 'Andorra', capital: 'Andorra la Vella', population: '79K', region: 'Europe', flag: '🇦🇩', lat: 42.5063, lng: 1.5218, description: 'A tiny, independent principality situated between France and Spain in the Pyrenees mountains.', area: '468', currency: 'Euro', languages: ['Catalan'], borders: ['France', 'Spain'], gdp: '$3.3B', timeZone: 'UTC+1', callingCode: '+376', driveSide: 'Right' },
  { id: '5', name: 'Angola', capital: 'Luanda', population: '35.6M', region: 'Africa', flag: '🇦🇴', lat: -8.8390, lng: 13.2894, description: 'A Southern African nation with vast natural resources, diverse terrain, and a distinct Portuguese colonial history.', area: '1.25M', currency: 'Kwanza', languages: ['Portuguese'], borders: ['Namibia', 'DR Congo', 'Zambia', 'Congo'], gdp: '$106B', timeZone: 'UTC+1', callingCode: '+244', driveSide: 'Right' },
  { id: '6', name: 'Antigua and Barbuda', capital: 'Saint John\'s', population: '93K', region: 'North America', flag: '🇦🇬', lat: 17.1274, lng: -61.8468, description: 'An independent Commonwealth country comprising its 2 namesake islands and several smaller ones.', area: '442', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$1.7B', timeZone: 'UTC-4', callingCode: '+1-268', driveSide: 'Left' },
  { id: '7', name: 'Argentina', capital: 'Buenos Aires', population: '46.2M', region: 'South America', flag: '🇦🇷', lat: -34.6037, lng: -58.3816, description: 'A massive South American nation with terrain encompassing Andes mountains, glacial lakes, and Pampas grassland.', area: '2.78M', currency: 'Argentine peso', languages: ['Spanish'], borders: ['Chile', 'Bolivia', 'Paraguay', 'Brazil', 'Uruguay'], gdp: '$632B', timeZone: 'UTC-3', callingCode: '+54', driveSide: 'Right' },
  { id: '8', name: 'Armenia', capital: 'Yerevan', population: '2.8M', region: 'Asia', flag: '🇦🇲', lat: 40.1792, lng: 44.4991, description: 'A nation in the South Caucasus region of Eurasia, the first country to establish Christianity as its state religion.', area: '29.7K', currency: 'Dram', languages: ['Armenian'], borders: ['Turkey', 'Georgia', 'Azerbaijan', 'Iran'], gdp: '$19.5B', timeZone: 'UTC+4', callingCode: '+374', driveSide: 'Right' },
  { id: '9', name: 'Australia', capital: 'Canberra', population: '26M', region: 'Oceania', flag: '🇦🇺', lat: -35.2809, lng: 149.1300, description: 'The largest country in Oceania, comprising the mainland of the Australian continent and Tasmania.', area: '7.69M', currency: 'Australian dollar', languages: ['English'], borders: [], gdp: '$1.7T', timeZone: 'UTC+8 to +11', callingCode: '+61', driveSide: 'Left' },
  { id: '10', name: 'Austria', capital: 'Vienna', population: '9M', region: 'Europe', flag: '🇦🇹', lat: 48.2082, lng: 16.3738, description: 'A landlocked East Alpine country in the southern part of Central Europe, famous for its music and architecture.', area: '83.8K', currency: 'Euro', languages: ['German'], borders: ['Germany', 'Czechia', 'Slovakia', 'Hungary', 'Slovenia', 'Italy', 'Switzerland', 'Liechtenstein'], gdp: '$471B', timeZone: 'UTC+1', callingCode: '+43', driveSide: 'Right' },
  { id: '11', name: 'Azerbaijan', capital: 'Baku', population: '10.1M', region: 'Asia', flag: '🇦🇿', lat: 40.4093, lng: 49.8671, description: 'A nation and former Soviet republic, bounded by the Caspian Sea and Caucasus Mountains.', area: '86.6K', currency: 'Manat', languages: ['Azerbaijani'], borders: ['Russia', 'Georgia', 'Armenia', 'Iran', 'Turkey'], gdp: '$78B', timeZone: 'UTC+4', callingCode: '+994', driveSide: 'Right' },
  
  // --- B ---
  { id: '12', name: 'Bahamas', capital: 'Nassau', population: '409K', region: 'North America', flag: '🇧🇸', lat: 25.0443, lng: -77.3504, description: 'A coral-based archipelago in the Atlantic Ocean, comprising 700 islands and cays.', area: '13.9K', currency: 'Bahamian dollar', languages: ['English'], borders: [], gdp: '$12.9B', timeZone: 'UTC-5', callingCode: '+1-242', driveSide: 'Left' },
  { id: '13', name: 'Bahrain', capital: 'Manama', population: '1.5M', region: 'Asia', flag: '🇧🇭', lat: 26.2285, lng: 50.5860, description: 'A sovereign state in the Persian Gulf, comprising a small archipelago made up of 50 natural islands.', area: '778', currency: 'Bahraini dinar', languages: ['Arabic'], borders: [], gdp: '$44B', timeZone: 'UTC+3', callingCode: '+973', driveSide: 'Right' },
  { id: '14', name: 'Bangladesh', capital: 'Dhaka', population: '171M', region: 'Asia', flag: '🇧🇩', lat: 23.8103, lng: 90.4125, description: 'A country in South Asia, located in the delta of the Padma (Ganges) and Jamuna (Brahmaputra) rivers.', area: '148K', currency: 'Taka', languages: ['Bengali'], borders: ['India', 'Myanmar'], gdp: '$460B', timeZone: 'UTC+6', callingCode: '+880', driveSide: 'Left' },
  { id: '15', name: 'Barbados', capital: 'Bridgetown', population: '281K', region: 'North America', flag: '🇧🇧', lat: 13.1132, lng: -59.5988, description: 'An eastern Caribbean island and an independent British Commonwealth nation.', area: '430', currency: 'Barbadian dollar', languages: ['English'], borders: [], gdp: '$5.6B', timeZone: 'UTC-4', callingCode: '+1-246', driveSide: 'Left' },
  { id: '16', name: 'Belarus', capital: 'Minsk', population: '9.2M', region: 'Europe', flag: '🇧🇾', lat: 53.9006, lng: 27.5590, description: 'A landlocked country in Eastern Europe known for its Stalinist architecture, grand fortifications, and primeval forests.', area: '207K', currency: 'Belarusian ruble', languages: ['Belarusian', 'Russian'], borders: ['Latvia', 'Lithuania', 'Poland', 'Ukraine', 'Russia'], gdp: '$72B', timeZone: 'UTC+3', callingCode: '+375', driveSide: 'Right' },
  { id: '17', name: 'Belgium', capital: 'Brussels', population: '11.7M', region: 'Europe', flag: '🇧🇪', lat: 50.8503, lng: 4.3517, description: 'A country in Western Europe known for medieval towns, Renaissance architecture, and being the headquarters of the EU.', area: '30.5K', currency: 'Euro', languages: ['Dutch', 'French', 'German'], borders: ['France', 'Germany', 'Luxembourg', 'Netherlands'], gdp: '$578B', timeZone: 'UTC+1', callingCode: '+32', driveSide: 'Right' },
  { id: '18', name: 'Belize', capital: 'Belmopan', population: '412K', region: 'North America', flag: '🇧🇿', lat: 17.2510, lng: -88.7590, description: 'A nation on the eastern coast of Central America, with Caribbean Sea shorelines to the east and dense jungle to the west.', area: '22.9K', currency: 'Belize dollar', languages: ['English'], borders: ['Mexico', 'Guatemala'], gdp: '$2.8B', timeZone: 'UTC-6', callingCode: '+501', driveSide: 'Right' },
  { id: '19', name: 'Benin', capital: 'Porto-Novo', population: '13.3M', region: 'Africa', flag: '🇧🇯', lat: 6.4969, lng: 2.6289, description: 'A French-speaking West African nation and birthplace of the vodun (voodoo) religion.', area: '114K', currency: 'West African CFA franc', languages: ['French'], borders: ['Togo', 'Nigeria', 'Burkina Faso', 'Niger'], gdp: '$17B', timeZone: 'UTC+1', callingCode: '+229', driveSide: 'Right' },
  { id: '20', name: 'Bhutan', capital: 'Thimphu', population: '782K', region: 'Asia', flag: '🇧🇹', lat: 27.4728, lng: 89.6393, description: 'A Buddhist kingdom on the Himalayas’ eastern edge, known for its monasteries, fortresses (or dzongs), and dramatic landscapes.', area: '38.3K', currency: 'Ngultrum', languages: ['Dzongkha'], borders: ['China', 'India'], gdp: '$2.5B', timeZone: 'UTC+6', callingCode: '+975', driveSide: 'Left' },
  { id: '21', name: 'Bolivia', capital: 'Sucre', population: '12.2M', region: 'South America', flag: '🇧🇴', lat: -19.0333, lng: -65.2627, description: 'A diverse nation in central South America, home to the Andes, the Atacama Desert, and Amazon Basin rainforest.', area: '1.1M', currency: 'Boliviano', languages: ['Spanish', 'Quechua', 'Aymara'], borders: ['Brazil', 'Paraguay', 'Argentina', 'Chile', 'Peru'], gdp: '$43B', timeZone: 'UTC-4', callingCode: '+591', driveSide: 'Right' },
  { id: '22', name: 'Bosnia and Herzegovina', capital: 'Sarajevo', population: '3.2M', region: 'Europe', flag: '🇧🇦', lat: 43.8563, lng: 18.4131, description: 'A country on the Balkan Peninsula in southeastern Europe, known for its rivers, mountains, and religious diversity.', area: '51.2K', currency: 'Convertible mark', languages: ['Bosnian', 'Croatian', 'Serbian'], borders: ['Croatia', 'Serbia', 'Montenegro'], gdp: '$24.5B', timeZone: 'UTC+1', callingCode: '+387', driveSide: 'Right' },
  { id: '23', name: 'Botswana', capital: 'Gaborone', population: '2.6M', region: 'Africa', flag: '🇧🇼', lat: -24.6282, lng: 25.9231, description: 'A landlocked country in Southern Africa defined by the Kalahari Desert and the Okavango Delta.', area: '581K', currency: 'Pula', languages: ['English', 'Tswana'], borders: ['Namibia', 'Zimbabwe', 'South Africa', 'Zambia'], gdp: '$20B', timeZone: 'UTC+2', callingCode: '+267', driveSide: 'Left' },
  { id: '24', name: 'Brazil', capital: 'Brasília', population: '215.3M', region: 'South America', flag: '🇧🇷', lat: -15.7975, lng: -47.8919, description: 'The largest country in South America, home to the Amazon Rainforest and the vibrant city of Rio de Janeiro.', area: '8.51M', currency: 'Brazilian real', languages: ['Portuguese'], borders: ['Argentina', 'Bolivia', 'Colombia', 'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela'], gdp: '$1.9T', timeZone: 'UTC-2 to -5', callingCode: '+55', driveSide: 'Right' },
  { id: '25', name: 'Brunei', capital: 'Bandar Seri Begawan', population: '449K', region: 'Asia', flag: '🇧🇳', lat: 4.9031, lng: 114.9398, description: 'A tiny nation on the island of Borneo, in 2 distinct sections surrounded by Malaysia and the South China Sea.', area: '5.7K', currency: 'Brunei dollar', languages: ['Malay'], borders: ['Malaysia'], gdp: '$16B', timeZone: 'UTC+8', callingCode: '+673', driveSide: 'Left' },
  { id: '26', name: 'Bulgaria', capital: 'Sofia', population: '6.5M', region: 'Europe', flag: '🇧🇬', lat: 42.6977, lng: 23.3219, description: 'A Balkan nation with diverse terrain encompassing Black Sea coastline, a mountainous interior, and rivers.', area: '110K', currency: 'Lev', languages: ['Bulgarian'], borders: ['Romania', 'Serbia', 'North Macedonia', 'Greece', 'Turkey'], gdp: '$89B', timeZone: 'UTC+2', callingCode: '+359', driveSide: 'Right' },
  { id: '27', name: 'Burkina Faso', capital: 'Ouagadougou', population: '22.6M', region: 'Africa', flag: '🇧🇫', lat: 12.3714, lng: -1.5197, description: 'A landlocked country in West Africa known for its significant reserves of gold.', area: '274K', currency: 'West African CFA franc', languages: ['French'], borders: ['Mali', 'Niger', 'Benin', 'Togo', 'Ghana', 'Côte d\'Ivoire'], gdp: '$19B', timeZone: 'UTC+0', callingCode: '+226', driveSide: 'Right' },
  { id: '28', name: 'Burundi', capital: 'Gitega', population: '12.8M', region: 'Africa', flag: '🇧🇮', lat: -3.4273, lng: 29.9246, description: 'A landlocked country in the Great Rift Valley where the African Great Lakes region and East Africa converge.', area: '27.8K', currency: 'Burundian franc', languages: ['Kirundi', 'French'], borders: ['Rwanda', 'Tanzania', 'DR Congo'], gdp: '$3.3B', timeZone: 'UTC+2', callingCode: '+257', driveSide: 'Right' },

  // --- C ---
  { id: '29', name: 'Cabo Verde', capital: 'Praia', population: '593K', region: 'Africa', flag: '🇨🇻', lat: 14.9330, lng: -23.5133, description: 'An island country spanning an archipelago of 10 volcanic islands in the central Atlantic Ocean.', area: '4K', currency: 'Cape Verdean escudo', languages: ['Portuguese'], borders: [], gdp: '$2.3B', timeZone: 'UTC-1', callingCode: '+238', driveSide: 'Right' },
  { id: '30', name: 'Cambodia', capital: 'Phnom Penh', population: '16.7M', region: 'Asia', flag: '🇰🇭', lat: 11.5564, lng: 104.9282, description: 'A Southeast Asian nation whose landscape spans low-lying plains, the Mekong Delta, mountains, and Gulf of Thailand coastline.', area: '181K', currency: 'Riel', languages: ['Khmer'], borders: ['Thailand', 'Laos', 'Vietnam'], gdp: '$29B', timeZone: 'UTC+7', callingCode: '+855', driveSide: 'Right' },
  { id: '31', name: 'Cameroon', capital: 'Yaoundé', population: '27.9M', region: 'Africa', flag: '🇨🇲', lat: 3.8480, lng: 11.5021, description: 'A country in Central Africa often called "Africa in miniature" for its geological and cultural diversity.', area: '475K', currency: 'Central African CFA franc', languages: ['French', 'English'], borders: ['Nigeria', 'Chad', 'Central African Republic', 'Congo', 'Gabon', 'Equatorial Guinea'], gdp: '$45B', timeZone: 'UTC+1', callingCode: '+237', driveSide: 'Right' },
  { id: '32', name: 'Canada', capital: 'Ottawa', population: '38.9M', region: 'North America', flag: '🇨🇦', lat: 45.4215, lng: -75.6972, description: 'A vast North American nation with diverse landscapes ranging from the Arctic tundra to the Rocky Mountains.', area: '9.98M', currency: 'Canadian dollar', languages: ['English', 'French'], borders: ['United States'], gdp: '$2.1T', timeZone: 'UTC-3.5 to -8', callingCode: '+1', driveSide: 'Right' },
  { id: '33', name: 'Central African Republic', capital: 'Bangui', population: '5.5M', region: 'Africa', flag: '🇨🇫', lat: 4.3947, lng: 18.5582, description: 'A landlocked country in Central Africa rich in diamonds, gold, oil, and uranium, but facing political instability.', area: '622K', currency: 'Central African CFA franc', languages: ['French', 'Sango'], borders: ['Chad', 'Sudan', 'South Sudan', 'DR Congo', 'Congo', 'Cameroon'], gdp: '$2.5B', timeZone: 'UTC+1', callingCode: '+236', driveSide: 'Right' },
  { id: '34', name: 'Chad', capital: 'N\'Djamena', population: '17.7M', region: 'Africa', flag: '🇹🇩', lat: 12.1348, lng: 15.0557, description: 'A landlocked country in north-central Africa, home to the Sahara Desert, a Sahelian belt, and the Sudanian Savanna.', area: '1.28M', currency: 'Central African CFA franc', languages: ['French', 'Arabic'], borders: ['Libya', 'Sudan', 'Central African Republic', 'Cameroon', 'Nigeria', 'Niger'], gdp: '$12B', timeZone: 'UTC+1', callingCode: '+235', driveSide: 'Right' },
  { id: '35', name: 'Chile', capital: 'Santiago', population: '19.6M', region: 'South America', flag: '🇨🇱', lat: -33.4489, lng: -70.6693, description: 'A long, narrow country stretching along South America\'s western edge, with more than 6,000km of Pacific Ocean coastline.', area: '756K', currency: 'Chilean peso', languages: ['Spanish'], borders: ['Peru', 'Bolivia', 'Argentina'], gdp: '$317B', timeZone: 'UTC-3 to -5', callingCode: '+56', driveSide: 'Right' },
  { id: '36', name: 'China', capital: 'Beijing', population: '1.42B', region: 'Asia', flag: '🇨🇳', lat: 39.9042, lng: 116.4074, description: 'One of the world\'s oldest civilizations, known for its diverse terrain, ancient history, and rapid modern development.', area: '9.6M', currency: 'Renminbi', languages: ['Mandarin'], borders: ['Mongolia', 'Russia', 'North Korea', 'Vietnam', 'Laos', 'Myanmar', 'India', 'Bhutan', 'Nepal', 'Pakistan', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan', 'Kazakhstan'], gdp: '$18T', timeZone: 'UTC+8', callingCode: '+86', driveSide: 'Right' },
  { id: '37', name: 'Colombia', capital: 'Bogotá', population: '51.8M', region: 'South America', flag: '🇨🇴', lat: 4.7110, lng: -74.0721, description: 'A country at the northern tip of South America with diverse landscapes of rainforests, mountains, and coffee plantations.', area: '1.14M', currency: 'Colombian peso', languages: ['Spanish'], borders: ['Panama', 'Venezuela', 'Brazil', 'Peru', 'Ecuador'], gdp: '$343B', timeZone: 'UTC-5', callingCode: '+57', driveSide: 'Right' },
  { id: '38', name: 'Comoros', capital: 'Moroni', population: '836K', region: 'Africa', flag: '🇰🇲', lat: -11.7172, lng: 43.2473, description: 'A volcanic archipelago off Africa’s east coast, in the warm Indian Ocean waters of the Mozambique Channel.', area: '1.8K', currency: 'Comorian franc', languages: ['Comorian', 'French', 'Arabic'], borders: [], gdp: '$1.3B', timeZone: 'UTC+3', callingCode: '+269', driveSide: 'Right' },
  { id: '39', name: 'Republic of the Congo', capital: 'Brazzaville', population: '6M', region: 'Africa', flag: '🇨🇬', lat: -4.2634, lng: 15.2429, description: 'Also known as the Congo-Brazzaville, featuring vast swaths of tropical rainforest and reserves for gorillas.', area: '342K', currency: 'Central African CFA franc', languages: ['French'], borders: ['Gabon', 'Cameroon', 'Central African Republic', 'DR Congo', 'Angola'], gdp: '$14B', timeZone: 'UTC+1', callingCode: '+242', driveSide: 'Right' },
  { id: '40', name: 'DR Congo', capital: 'Kinshasa', population: '99M', region: 'Africa', flag: '🇨🇩', lat: -4.4419, lng: 15.2663, description: 'The Democratic Republic of the Congo, the second largest country in Africa, known for its vast mineral wealth and rainforest.', area: '2.34M', currency: 'Congolese franc', languages: ['French'], borders: ['Congo', 'Central African Republic', 'South Sudan', 'Uganda', 'Rwanda', 'Burundi', 'Tanzania', 'Zambia', 'Angola'], gdp: '$64B', timeZone: 'UTC+1 to +2', callingCode: '+243', driveSide: 'Right' },
  { id: '41', name: 'Costa Rica', capital: 'San José', population: '5.2M', region: 'North America', flag: '🇨🇷', lat: 9.9281, lng: -84.0907, description: 'A rugged, rainforested Central American country with coastlines on the Caribbean and Pacific.', area: '51.1K', currency: 'Costa Rican colón', languages: ['Spanish'], borders: ['Nicaragua', 'Panama'], gdp: '$68B', timeZone: 'UTC-6', callingCode: '+506', driveSide: 'Right' },
  { id: '42', name: 'Côte d\'Ivoire', capital: 'Yamoussoukro', population: '28M', region: 'Africa', flag: '🇨🇮', lat: 6.8276, lng: -5.2893, description: 'A West African country with beach resorts, rainforests, and a French-colonial legacy.', area: '322K', currency: 'West African CFA franc', languages: ['French'], borders: ['Liberia', 'Guinea', 'Mali', 'Burkina Faso', 'Ghana'], gdp: '$70B', timeZone: 'UTC+0', callingCode: '+225', driveSide: 'Right' },
  { id: '43', name: 'Croatia', capital: 'Zagreb', population: '3.9M', region: 'Europe', flag: '🇭🇷', lat: 45.8150, lng: 15.9819, description: 'A country at the crossroads of Central and Southeast Europe, with a long coastline on the Adriatic Sea.', area: '56.5K', currency: 'Euro', languages: ['Croatian'], borders: ['Slovenia', 'Hungary', 'Serbia', 'Bosnia and Herzegovina', 'Montenegro'], gdp: '$71B', timeZone: 'UTC+1', callingCode: '+385', driveSide: 'Right' },
  { id: '44', name: 'Cuba', capital: 'Havana', population: '11.2M', region: 'North America', flag: '🇨🇺', lat: 23.1136, lng: -82.3666, description: 'The largest island nation in the Caribbean, known for its white-sand beaches, rolling mountains, cigars and rum.', area: '110K', currency: 'Cuban peso', languages: ['Spanish'], borders: [], gdp: '$107B', timeZone: 'UTC-5', callingCode: '+53', driveSide: 'Right' },
  { id: '45', name: 'Cyprus', capital: 'Nicosia', population: '1.2M', region: 'Europe', flag: '🇨🇾', lat: 35.1856, lng: 33.3823, description: 'An island country in the Eastern Mediterranean known for its mineral wealth, wines, and natural beauty.', area: '9.2K', currency: 'Euro', languages: ['Greek', 'Turkish'], borders: [], gdp: '$28B', timeZone: 'UTC+2', callingCode: '+357', driveSide: 'Left' },
  { id: '46', name: 'Czechia', capital: 'Prague', population: '10.5M', region: 'Europe', flag: '🇨🇿', lat: 50.0755, lng: 14.4378, description: 'Also known as the Czech Republic, a landlocked country in Central Europe known for its ornate castles and native beers.', area: '78.8K', currency: 'Czech koruna', languages: ['Czech'], borders: ['Germany', 'Austria', 'Slovakia', 'Poland'], gdp: '$290B', timeZone: 'UTC+1', callingCode: '+420', driveSide: 'Right' },

  // --- D ---
  { id: '47', name: 'Denmark', capital: 'Copenhagen', population: '5.9M', region: 'Europe', flag: '🇩🇰', lat: 55.6761, lng: 12.5683, description: 'A Scandinavian country comprising the Jutland Peninsula and numerous islands, linked to Sweden via the Öresund bridge.', area: '42.9K', currency: 'Danish krone', languages: ['Danish'], borders: ['Germany'], gdp: '$395B', timeZone: 'UTC+1', callingCode: '+45', driveSide: 'Right' },
  { id: '48', name: 'Djibouti', capital: 'Djibouti City', population: '1.1M', region: 'Africa', flag: '🇩🇯', lat: 11.5721, lng: 43.1456, description: 'A country located in the Horn of Africa, mostly comprising scrubland, volcanic formations, and Gulf of Aden beaches.', area: '23.2K', currency: 'Djiboutian franc', languages: ['French', 'Arabic'], borders: ['Eritrea', 'Ethiopia', 'Somalia'], gdp: '$3.5B', timeZone: 'UTC+3', callingCode: '+253', driveSide: 'Right' },
  { id: '49', name: 'Dominica', capital: 'Roseau', population: '72K', region: 'North America', flag: '🇩🇲', lat: 15.3092, lng: -61.3794, description: 'A mountainous Caribbean island nation with natural hot springs and tropical rainforests.', area: '751', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$0.6B', timeZone: 'UTC-4', callingCode: '+1-767', driveSide: 'Left' },
  { id: '50', name: 'Dominican Republic', capital: 'Santo Domingo', population: '11.2M', region: 'North America', flag: '🇩🇴', lat: 18.4861, lng: -69.9312, description: 'A Caribbean nation that shares the island of Hispaniola with Haiti to the west.', area: '48.6K', currency: 'Dominican peso', languages: ['Spanish'], borders: ['Haiti'], gdp: '$113B', timeZone: 'UTC-4', callingCode: '+1-809', driveSide: 'Right' },
  
  // --- E ---
  { id: '52', name: 'Ecuador', capital: 'Quito', population: '18M', region: 'South America', flag: '🇪🇨', lat: -0.1807, lng: -78.4678, description: 'A country straddling the equator on South America’s west coast, with diverse landscapes including the Amazon and Andean highlands.', area: '283K', currency: 'United States dollar', languages: ['Spanish'], borders: ['Colombia', 'Peru'], gdp: '$115B', timeZone: 'UTC-5', callingCode: '+593', driveSide: 'Right' },
  { id: '53', name: 'Egypt', capital: 'Cairo', population: '111M', region: 'Africa', flag: '🇪🇬', lat: 30.0444, lng: 31.2357, description: 'A country linking northeast Africa with the Middle East, home to millennia-old monuments like the Pyramids.', area: '1M', currency: 'Egyptian pound', languages: ['Arabic'], borders: ['Libya', 'Sudan', 'Israel', 'Palestine'], gdp: '$476B', timeZone: 'UTC+2', callingCode: '+20', driveSide: 'Right' },
  { id: '54', name: 'El Salvador', capital: 'San Salvador', population: '6.3M', region: 'North America', flag: '🇸🇻', lat: 13.6929, lng: -89.2182, description: 'A small Central American nation known for its Pacific Ocean beaches, surf spots, and mountainous landscape.', area: '21K', currency: 'United States dollar', languages: ['Spanish'], borders: ['Guatemala', 'Honduras'], gdp: '$32B', timeZone: 'UTC-6', callingCode: '+503', driveSide: 'Right' },
  { id: '55', name: 'Equatorial Guinea', capital: 'Malabo', population: '1.6M', region: 'Africa', flag: '🇬🇶', lat: 3.7504, lng: 8.7371, description: 'A Central African country comprising the Rio Muni mainland and 5 volcanic offshore islands.', area: '28K', currency: 'Central African CFA franc', languages: ['Spanish', 'French', 'Portuguese'], borders: ['Cameroon', 'Gabon'], gdp: '$11B', timeZone: 'UTC+1', callingCode: '+240', driveSide: 'Right' },
  { id: '56', name: 'Eritrea', capital: 'Asmara', population: '3.6M', region: 'Africa', flag: '🇪🇷', lat: 15.3229, lng: 38.9251, description: 'A northeast African country on the Red Sea coast, with colonial Italian architecture in its capital.', area: '117K', currency: 'Nakfa', languages: ['Tigrinya', 'Arabic', 'English'], borders: ['Sudan', 'Ethiopia', 'Djibouti'], gdp: '$2.1B', timeZone: 'UTC+3', callingCode: '+291', driveSide: 'Right' },
  { id: '57', name: 'Estonia', capital: 'Tallinn', population: '1.3M', region: 'Europe', flag: '🇪🇪', lat: 59.4370, lng: 24.7536, description: 'A country in Northern Europe, borders the Baltic Sea and Gulf of Finland, including more than 1,500 islands.', area: '45.2K', currency: 'Euro', languages: ['Estonian'], borders: ['Latvia', 'Russia'], gdp: '$38B', timeZone: 'UTC+2', callingCode: '+372', driveSide: 'Right' },
  { id: '58', name: 'Eswatini', capital: 'Mbabane', population: '1.2M', region: 'Africa', flag: '🇸🇿', lat: -26.3055, lng: 31.1367, description: 'A small, landlocked monarchy in Southern Africa, known for its wilderness reserves and traditional culture.', area: '17.3K', currency: 'Lilangeni', languages: ['Swazi', 'English'], borders: ['South Africa', 'Mozambique'], gdp: '$4.8B', timeZone: 'UTC+2', callingCode: '+268', driveSide: 'Left' },
  { id: '59', name: 'Ethiopia', capital: 'Addis Ababa', population: '123M', region: 'Africa', flag: '🇪🇹', lat: 9.0300, lng: 38.7400, description: 'A rugged, landlocked country in the Horn of Africa, with ancient culture and archaeological sites dating back 3 million years.', area: '1.1M', currency: 'Birr', languages: ['Amharic'], borders: ['Eritrea', 'Djibouti', 'Somalia', 'Kenya', 'South Sudan', 'Sudan'], gdp: '$126B', timeZone: 'UTC+3', callingCode: '+251', driveSide: 'Right' },
  
  // --- F ---
  { id: '60', name: 'Fiji', capital: 'Suva', population: '929K', region: 'Oceania', flag: '🇫🇯', lat: -18.1248, lng: 178.4501, description: 'An archipelago of more than 300 islands in the South Pacific, famed for rugged landscapes and coral reefs.', area: '18.2K', currency: 'Fijian dollar', languages: ['English', 'Fijian'], borders: [], gdp: '$5B', timeZone: 'UTC+12', callingCode: '+679', driveSide: 'Left' },
  { id: '61', name: 'Finland', capital: 'Helsinki', population: '5.5M', region: 'Europe', flag: '🇫🇮', lat: 60.1699, lng: 24.9384, description: 'A Northern European nation bordering Sweden, Norway and Russia, famous for the Northern Lights and thousands of lakes.', area: '338K', currency: 'Euro', languages: ['Finnish', 'Swedish'], borders: ['Sweden', 'Norway', 'Russia'], gdp: '$280B', timeZone: 'UTC+2', callingCode: '+358', driveSide: 'Right' },
  { id: '62', name: 'France', capital: 'Paris', population: '67.9M', region: 'Europe', flag: '🇫🇷', lat: 48.8566, lng: 2.3522, description: 'A Western European country encompassing medieval cities, alpine villages and Mediterranean beaches.', area: '551K', currency: 'Euro', languages: ['French'], borders: ['Belgium', 'Luxembourg', 'Germany', 'Switzerland', 'Italy', 'Spain', 'Andorra', 'Monaco'], gdp: '$2.7T', timeZone: 'UTC+1', callingCode: '+33', driveSide: 'Right' },
  
  // --- G ---
  { id: '63', name: 'Gabon', capital: 'Libreville', population: '2.3M', region: 'Africa', flag: '🇬🇦', lat: 0.4162, lng: 9.4673, description: 'A country along the Atlantic coast of Central Africa, with significant areas of protected parkland.', area: '267K', currency: 'Central African CFA franc', languages: ['French'], borders: ['Equatorial Guinea', 'Cameroon', 'Congo'], gdp: '$21B', timeZone: 'UTC+1', callingCode: '+241', driveSide: 'Right' },
  { id: '64', name: 'Gambia', capital: 'Banjul', population: '2.7M', region: 'Africa', flag: '🇬🇲', lat: 13.4549, lng: -16.5790, description: 'A small West African country, bounded by Senegal, with a narrow Atlantic coastline.', area: '10.6K', currency: 'Dalasi', languages: ['English'], borders: ['Senegal'], gdp: '$2.2B', timeZone: 'UTC+0', callingCode: '+220', driveSide: 'Right' },
  { id: '65', name: 'Georgia', capital: 'Tbilisi', population: '3.7M', region: 'Asia', flag: '🇬🇪', lat: 41.7151, lng: 44.8271, description: 'A country at the intersection of Europe and Asia, famous for its cave monasteries and ancient wine regions.', area: '69.7K', currency: 'Lari', languages: ['Georgian'], borders: ['Russia', 'Azerbaijan', 'Armenia', 'Turkey'], gdp: '$25B', timeZone: 'UTC+4', callingCode: '+995', driveSide: 'Right' },
  { id: '66', name: 'Germany', capital: 'Berlin', population: '84M', region: 'Europe', flag: '🇩🇪', lat: 52.5200, lng: 13.4050, description: 'A Western European country with a landscape of forests, rivers, mountain ranges and North Sea beaches.', area: '357K', currency: 'Euro', languages: ['German'], borders: ['Denmark', 'Poland', 'Czechia', 'Austria', 'Switzerland', 'France', 'Luxembourg', 'Belgium', 'Netherlands'], gdp: '$4T', timeZone: 'UTC+1', callingCode: '+49', driveSide: 'Right' },
  { id: '67', name: 'Ghana', capital: 'Accra', population: '33.4M', region: 'Africa', flag: '🇬🇭', lat: 5.6037, lng: -0.1870, description: 'A West African country known for its diverse wildlife, old forts, and secluded beaches.', area: '238K', currency: 'Cedi', languages: ['English'], borders: ['Côte d\'Ivoire', 'Burkina Faso', 'Togo'], gdp: '$77B', timeZone: 'UTC+0', callingCode: '+233', driveSide: 'Right' },
  { id: '68', name: 'Greece', capital: 'Athens', population: '10.4M', region: 'Europe', flag: '🇬🇷', lat: 37.9838, lng: 23.7275, description: 'A country in southeastern Europe with thousands of islands, considered the cradle of Western civilization.', area: '131K', currency: 'Euro', languages: ['Greek'], borders: ['Albania', 'North Macedonia', 'Bulgaria', 'Turkey'], gdp: '$219B', timeZone: 'UTC+2', callingCode: '+30', driveSide: 'Right' },
  { id: '69', name: 'Grenada', capital: 'Saint George\'s', population: '125K', region: 'North America', flag: '🇬🇩', lat: 12.0561, lng: -61.7488, description: 'A Caribbean country comprising a main island, also called Grenada, and smaller surrounding islands.', area: '348.5', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$1.2B', timeZone: 'UTC-4', callingCode: '+1-473', driveSide: 'Left' },
  { id: '70', name: 'Guatemala', capital: 'Guatemala City', population: '17.3M', region: 'North America', flag: '🇬🇹', lat: 14.6349, lng: -90.5069, description: 'A Central American country home to volcanoes, rainforests and ancient Mayan sites.', area: '108K', currency: 'Quetzal', languages: ['Spanish'], borders: ['Mexico', 'Belize', 'Honduras', 'El Salvador'], gdp: '$95B', timeZone: 'UTC-6', callingCode: '+502', driveSide: 'Right' },
  { id: '71', name: 'Guinea', capital: 'Conakry', population: '13.8M', region: 'Africa', flag: '🇬🇳', lat: 9.5092, lng: -13.7122, description: 'A country in West Africa, bordered on the west by the Atlantic Ocean, known for the Mount Nimba Strict Nature Reserve.', area: '245K', currency: 'Guinean franc', languages: ['French'], borders: ['Guinea-Bissau', 'Senegal', 'Mali', 'Côte d\'Ivoire', 'Liberia', 'Sierra Leone'], gdp: '$21B', timeZone: 'UTC+0', callingCode: '+224', driveSide: 'Right' },
  { id: '72', name: 'Guinea-Bissau', capital: 'Bissau', population: '2M', region: 'Africa', flag: '🇬🇼', lat: 11.8632, lng: -15.5991, description: 'A tropical country on West Africa’s Atlantic coast known for national parks and wildlife.', area: '36K', currency: 'West African CFA franc', languages: ['Portuguese'], borders: ['Senegal', 'Guinea'], gdp: '$1.6B', timeZone: 'UTC+0', callingCode: '+245', driveSide: 'Right' },
  { id: '73', name: 'Guyana', capital: 'Georgetown', population: '808K', region: 'South America', flag: '🇬🇾', lat: 6.8013, lng: -58.1551, description: 'A country on South America’s North Atlantic coast, defined by its dense rainforest.', area: '214K', currency: 'Guyanese dollar', languages: ['English'], borders: ['Venezuela', 'Brazil', 'Suriname'], gdp: '$14.5B', timeZone: 'UTC-4', callingCode: '+592', driveSide: 'Left' },
  { id: '74', name: 'Haiti', capital: 'Port-au-Prince', population: '11.5M', region: 'North America', flag: '🇭🇹', lat: 18.5944, lng: -72.3074, description: 'A Caribbean country that shares the island of Hispaniola with the Dominican Republic to its east.', area: '27.7K', currency: 'Gourde', languages: ['French', 'Haitian Creole'], borders: ['Dominican Republic'], gdp: '$21B', timeZone: 'UTC-5', callingCode: '+509', driveSide: 'Right' },
  { id: '75', name: 'Honduras', capital: 'Tegucigalpa', population: '10.4M', region: 'North America', flag: '🇭🇳', lat: 14.0723, lng: -87.1921, description: 'A Central American country with Caribbean Sea coastlines to the north and the Pacific Ocean to the south.', area: '112K', currency: 'Lempira', languages: ['Spanish'], borders: ['Guatemala', 'El Salvador', 'Nicaragua'], gdp: '$31B', timeZone: 'UTC-6', callingCode: '+504', driveSide: 'Right' },
  { id: '76', name: 'Hungary', capital: 'Budapest', population: '9.7M', region: 'Europe', flag: '🇭🇺', lat: 47.4979, lng: 19.0402, description: 'A landlocked country in Central Europe, known for its medieval architecture and thermal baths.', area: '93K', currency: 'Forint', languages: ['Hungarian'], borders: ['Slovakia', 'Ukraine', 'Romania', 'Serbia', 'Croatia', 'Slovenia', 'Austria'], gdp: '$178B', timeZone: 'UTC+1', callingCode: '+36', driveSide: 'Right' },
  
  // --- I ---
  { id: '77', name: 'Iceland', capital: 'Reykjavik', population: '372K', region: 'Europe', flag: '🇮🇸', lat: 64.1265, lng: -21.8174, description: 'A Nordic island nation, defined by its dramatic landscape with volcanoes, geysers, hot springs and lava fields.', area: '103K', currency: 'Icelandic króna', languages: ['Icelandic'], borders: [], gdp: '$27B', timeZone: 'UTC+0', callingCode: '+354', driveSide: 'Right' },
  { id: '78', name: 'India', capital: 'New Delhi', population: '1.4B', region: 'Asia', flag: '🇮🇳', lat: 28.6139, lng: 77.2090, description: 'A massive South Asian country with diverse terrain from Himalayan peaks to Indian Ocean coastline.', area: '3.28M', currency: 'Indian rupee', languages: ['Hindi', 'English'], borders: ['Pakistan', 'China', 'Nepal', 'Bhutan', 'Bangladesh', 'Myanmar'], gdp: '$3.4T', timeZone: 'UTC+5:30', callingCode: '+91', driveSide: 'Left' },
  { id: '79', name: 'Indonesia', capital: 'Jakarta', population: '275M', region: 'Asia', flag: '🇮🇩', lat: -6.2088, lng: 106.8456, description: 'A Southeast Asian nation made up of thousands of volcanic islands, home to hundreds of ethnic groups.', area: '1.9M', currency: 'Indonesian rupiah', languages: ['Indonesian'], borders: ['Malaysia', 'Papua New Guinea', 'Timor-Leste'], gdp: '$1.3T', timeZone: 'UTC+7 to +9', callingCode: '+62', driveSide: 'Left' },
  { id: '80', name: 'Iran', capital: 'Tehran', population: '88.5M', region: 'Asia', flag: '🇮🇷', lat: 35.6892, lng: 51.3890, description: 'A Middle Eastern country and home to one of the world\'s oldest civilizations, with ruins dating back to the Persian Empire.', area: '1.64M', currency: 'Iranian rial', languages: ['Persian'], borders: ['Iraq', 'Turkey', 'Armenia', 'Azerbaijan', 'Turkmenistan', 'Afghanistan', 'Pakistan'], gdp: '$388B', timeZone: 'UTC+3:30', callingCode: '+98', driveSide: 'Right' },
  { id: '81', name: 'Iraq', capital: 'Baghdad', population: '44.5M', region: 'Asia', flag: '🇮🇶', lat: 33.3152, lng: 44.3661, description: 'A country in Western Asia, bordered by Turkey to the north and the Persian Gulf to the southeast.', area: '438K', currency: 'Iraqi dinar', languages: ['Arabic', 'Kurdish'], borders: ['Turkey', 'Iran', 'Kuwait', 'Saudi Arabia', 'Jordan', 'Syria'], gdp: '$264B', timeZone: 'UTC+3', callingCode: '+964', driveSide: 'Right' },
  { id: '82', name: 'Ireland', capital: 'Dublin', population: '5M', region: 'Europe', flag: '🇮🇪', lat: 53.3498, lng: -6.2603, description: 'An island in the North Atlantic, known for its lush landscapes and rich Celtic history.', area: '70.2K', currency: 'Euro', languages: ['English', 'Irish'], borders: ['United Kingdom'], gdp: '$529B', timeZone: 'UTC+0', callingCode: '+353', driveSide: 'Left' },
  { id: '83', name: 'Israel', capital: 'Jerusalem', population: '9.5M', region: 'Asia', flag: '🇮🇱', lat: 31.7683, lng: 35.2137, description: 'A Middle Eastern country on the Mediterranean Sea regarded by Jews, Christians and Muslims as the biblical Holy Land.', area: '20.7K', currency: 'New Shekel', languages: ['Hebrew'], borders: ['Lebanon', 'Syria', 'Jordan', 'Egypt'], gdp: '$522B', timeZone: 'UTC+2', callingCode: '+972', driveSide: 'Right' },
  { id: '84', name: 'Italy', capital: 'Rome', population: '59M', region: 'Europe', flag: '🇮🇹', lat: 41.9028, lng: 12.4964, description: 'A European country with a long Mediterranean coastline, leaving a powerful mark on Western culture and cuisine.', area: '301K', currency: 'Euro', languages: ['Italian'], borders: ['France', 'Switzerland', 'Austria', 'Slovenia', 'San Marino', 'Vatican City'], gdp: '$2T', timeZone: 'UTC+1', callingCode: '+39', driveSide: 'Right' },
  
  // --- J ---
  { id: '85', name: 'Jamaica', capital: 'Kingston', population: '2.8M', region: 'North America', flag: '🇯🇲', lat: 18.0179, lng: -76.8099, description: 'A Caribbean island nation known for its reef-lined beaches, lush rainforests, and reggae music.', area: '10.9K', currency: 'Jamaican dollar', languages: ['English'], borders: [], gdp: '$17B', timeZone: 'UTC-5', callingCode: '+1-876', driveSide: 'Left' },
  { id: '86', name: 'Japan', capital: 'Tokyo', population: '125M', region: 'Asia', flag: '🇯🇵', lat: 35.6895, lng: 139.6917, description: 'An island country in East Asia known for its skyscrapers, imperial palaces, national parks, and shrines.', area: '377.9K', currency: 'Japanese yen', languages: ['Japanese'], borders: [], gdp: '$4.2T', timeZone: 'UTC+9', callingCode: '+81', driveSide: 'Left' },
  { id: '87', name: 'Jordan', capital: 'Amman', population: '11.2M', region: 'Asia', flag: '🇯🇴', lat: 31.9454, lng: 35.9284, description: 'An Arab nation on the east bank of the Jordan River, defined by ancient monuments, nature reserves and seaside resorts.', area: '89.3K', currency: 'Jordanian dinar', languages: ['Arabic'], borders: ['Syria', 'Iraq', 'Saudi Arabia', 'Israel', 'Palestine'], gdp: '$47B', timeZone: 'UTC+3', callingCode: '+962', driveSide: 'Right' },
  
  // --- K ---
  { id: '88', name: 'Kazakhstan', capital: 'Astana', population: '19.6M', region: 'Asia', flag: '🇰🇿', lat: 51.1694, lng: 71.4491, description: 'A Central Asian country and former Soviet republic, extending from the Caspian Sea in the west to the Altai Mountains.', area: '2.72M', currency: 'Tenge', languages: ['Kazakh', 'Russian'], borders: ['Russia', 'China', 'Kyrgyzstan', 'Uzbekistan', 'Turkmenistan'], gdp: '$220B', timeZone: 'UTC+5', callingCode: '+7', driveSide: 'Right' },
  { id: '89', name: 'Kenya', capital: 'Nairobi', population: '54M', region: 'Africa', flag: '🇰🇪', lat: -1.2921, lng: 36.8219, description: 'A country in East Africa with coastline on the Indian Ocean, encompassing savannah, lakelands, and the dramatic Great Rift Valley.', area: '580K', currency: 'Kenyan shilling', languages: ['Swahili', 'English'], borders: ['Ethiopia', 'Somalia', 'Tanzania', 'Uganda', 'South Sudan'], gdp: '$113B', timeZone: 'UTC+3', callingCode: '+254', driveSide: 'Left' },
  { id: '90', name: 'Kiribati', capital: 'Tarawa', population: '131K', region: 'Oceania', flag: '🇰🇮', lat: 1.4518, lng: 173.0015, description: 'An independent country in the central Pacific Ocean, comprising 33 coral atolls and isles stretching along the equator.', area: '811', currency: 'Australian dollar', languages: ['English', 'Gilbertese'], borders: [], gdp: '$223M', timeZone: 'UTC+12 to +14', callingCode: '+686', driveSide: 'Left' },
  { id: '91', name: 'Kuwait', capital: 'Kuwait City', population: '4.3M', region: 'Asia', flag: '🇰🇼', lat: 29.3759, lng: 47.9774, description: 'An Arab country on the Persian Gulf, possessing significant oil reserves and cultural heritage.', area: '17.8K', currency: 'Kuwaiti dinar', languages: ['Arabic'], borders: ['Iraq', 'Saudi Arabia'], gdp: '$184B', timeZone: 'UTC+3', callingCode: '+965', driveSide: 'Right' },
  { id: '92', name: 'Kyrgyzstan', capital: 'Bishkek', population: '6.6M', region: 'Asia', flag: '🇰🇬', lat: 42.8746, lng: 74.5698, description: 'A rugged Central Asian country along the Silk Road, known for the Tian Shan mountains.', area: '199K', currency: 'Som', languages: ['Kyrgyz', 'Russian'], borders: ['Kazakhstan', 'China', 'Tajikistan', 'Uzbekistan'], gdp: '$11B', timeZone: 'UTC+6', callingCode: '+996', driveSide: 'Right' },
  
  // --- L ---
  { id: '93', name: 'Laos', capital: 'Vientiane', population: '7.5M', region: 'Asia', flag: '🇱🇦', lat: 17.9757, lng: 102.6331, description: 'A Southeast Asian country traversed by the Mekong River and known for mountainous terrain and Buddhist monasteries.', area: '236K', currency: 'Kip', languages: ['Lao'], borders: ['China', 'Vietnam', 'Cambodia', 'Thailand', 'Myanmar'], gdp: '$15B', timeZone: 'UTC+7', callingCode: '+856', driveSide: 'Right' },
  { id: '94', name: 'Latvia', capital: 'Riga', population: '1.9M', region: 'Europe', flag: '🇱🇻', lat: 56.9496, lng: 24.1052, description: 'A country on the Baltic Sea between Lithuania and Estonia, known for its wide beaches and dense forests.', area: '64.5K', currency: 'Euro', languages: ['Latvian'], borders: ['Estonia', 'Russia', 'Belarus', 'Lithuania'], gdp: '$41B', timeZone: 'UTC+2', callingCode: '+371', driveSide: 'Right' },
  { id: '95', name: 'Lebanon', capital: 'Beirut', population: '5.5M', region: 'Asia', flag: '🇱🇧', lat: 33.8938, lng: 35.5018, description: 'A country with a long coastline on the eastern Mediterranean, known for its history, cuisine, and cedar forests.', area: '10.4K', currency: 'Lebanese pound', languages: ['Arabic'], borders: ['Syria', 'Israel'], gdp: '$23B', timeZone: 'UTC+2', callingCode: '+961', driveSide: 'Right' },
  { id: '96', name: 'Lesotho', capital: 'Maseru', population: '2.3M', region: 'Africa', flag: '🇱🇸', lat: -29.3151, lng: 27.4869, description: 'A high-altitude, landlocked kingdom encircled by South Africa, crisscrossed by a network of rivers and mountain ranges.', area: '30.3K', currency: 'Loti', languages: ['Sotho', 'English'], borders: ['South Africa'], gdp: '$2.5B', timeZone: 'UTC+2', callingCode: '+266', driveSide: 'Left' },
  { id: '97', name: 'Liberia', capital: 'Monrovia', population: '5.3M', region: 'Africa', flag: '🇱🇷', lat: 6.3005, lng: -10.7969, description: 'A country on the West African coast, founded by freed slaves from the US, known for its lush rainforests.', area: '111K', currency: 'Liberian dollar', languages: ['English'], borders: ['Sierra Leone', 'Guinea', 'Côte d\'Ivoire'], gdp: '$4B', timeZone: 'UTC+0', callingCode: '+231', driveSide: 'Right' },
  { id: '98', name: 'Libya', capital: 'Tripoli', population: '6.8M', region: 'Africa', flag: '🇱🇾', lat: 32.8872, lng: 13.1913, description: 'A country in the Maghreb region of North Africa, bordered by the Mediterranean Sea to the north.', area: '1.76M', currency: 'Libyan dinar', languages: ['Arabic'], borders: ['Egypt', 'Sudan', 'Chad', 'Niger', 'Algeria', 'Tunisia'], gdp: '$45B', timeZone: 'UTC+2', callingCode: '+218', driveSide: 'Right' },
  { id: '99', name: 'Liechtenstein', capital: 'Vaduz', population: '39K', region: 'Europe', flag: '🇱🇮', lat: 47.1410, lng: 9.5209, description: 'A German-speaking, 25km-long principality between Austria and Switzerland known for its medieval castles.', area: '160', currency: 'Swiss franc', languages: ['German'], borders: ['Switzerland', 'Austria'], gdp: '$6.7B', timeZone: 'UTC+1', callingCode: '+423', driveSide: 'Right' },
  { id: '100', name: 'Lithuania', capital: 'Vilnius', population: '2.8M', region: 'Europe', flag: '🇱🇹', lat: 54.6872, lng: 25.2797, description: 'The southernmost of Europe’s Baltic states, known for its medieval old towns and amber jewelry.', area: '65.3K', currency: 'Euro', languages: ['Lithuanian'], borders: ['Latvia', 'Belarus', 'Poland', 'Russia'], gdp: '$70B', timeZone: 'UTC+2', callingCode: '+370', driveSide: 'Right' },
  { id: '101', name: 'Luxembourg', capital: 'Luxembourg City', population: '650K', region: 'Europe', flag: '🇱🇺', lat: 49.6116, lng: 6.1319, description: 'A small European country surrounded by Belgium, France and Germany, known for its fortified medieval old town.', area: '2.5K', currency: 'Euro', languages: ['Luxembourgish', 'French', 'German'], borders: ['Belgium', 'Germany', 'France'], gdp: '$82B', timeZone: 'UTC+1', callingCode: '+352', driveSide: 'Right' },
  
  // --- M ---
  { id: '102', name: 'Madagascar', capital: 'Antananarivo', population: '29.6M', region: 'Africa', flag: '🇲🇬', lat: -18.8792, lng: 47.5079, description: 'A huge island nation off the southeast coast of Africa, home to thousands of animal species found nowhere else.', area: '587K', currency: 'Ariary', languages: ['Malagasy', 'French'], borders: [], gdp: '$15B', timeZone: 'UTC+3', callingCode: '+261', driveSide: 'Right' },
  { id: '103', name: 'Malawi', capital: 'Lilongwe', population: '20.4M', region: 'Africa', flag: '🇲🇼', lat: -13.9626, lng: 33.7741, description: 'A landlocked country in southeastern Africa, defined by its topography of highlands split by the Great Rift Valley.', area: '118K', currency: 'Malawian kwacha', languages: ['English', 'Chichewa'], borders: ['Tanzania', 'Mozambique', 'Zambia'], gdp: '$13B', timeZone: 'UTC+2', callingCode: '+265', driveSide: 'Left' },
  { id: '104', name: 'Malaysia', capital: 'Kuala Lumpur', population: '33.9M', region: 'Asia', flag: '🇲🇾', lat: 3.1390, lng: 101.6869, description: 'A Southeast Asian country occupying parts of the Malay Peninsula and the island of Borneo.', area: '329K', currency: 'Ringgit', languages: ['Malay'], borders: ['Thailand', 'Indonesia', 'Brunei'], gdp: '$406B', timeZone: 'UTC+8', callingCode: '+60', driveSide: 'Left' },
  { id: '105', name: 'Maldives', capital: 'Malé', population: '523K', region: 'Asia', flag: '🇲🇻', lat: 4.1755, lng: 73.5093, description: 'A tropical nation in the Indian Ocean composed of 26 ring-shaped atolls, which are made up of more than 1,000 coral islands.', area: '300', currency: 'Maldivian rufiyaa', languages: ['Dhivehi'], borders: [], gdp: '$6B', timeZone: 'UTC+5', callingCode: '+960', driveSide: 'Left' },
  { id: '106', name: 'Mali', capital: 'Bamako', population: '22.5M', region: 'Africa', flag: '🇲🇱', lat: 12.6392, lng: -8.0029, description: 'A landlocked country in West Africa, home to the ancient city of Timbuktu.', area: '1.24M', currency: 'West African CFA franc', languages: ['French'], borders: ['Algeria', 'Niger', 'Burkina Faso', 'Côte d\'Ivoire', 'Guinea', 'Senegal', 'Mauritania'], gdp: '$18B', timeZone: 'UTC+0', callingCode: '+223', driveSide: 'Right' },
  { id: '107', name: 'Malta', capital: 'Valletta', population: '533K', region: 'Europe', flag: '🇲🇹', lat: 35.8992, lng: 14.5141, description: 'An archipelago in the central Mediterranean between Sicily and the North African coast.', area: '316', currency: 'Euro', languages: ['Maltese', 'English'], borders: [], gdp: '$17B', timeZone: 'UTC+1', callingCode: '+356', driveSide: 'Left' },
  { id: '108', name: 'Marshall Islands', capital: 'Majuro', population: '41K', region: 'Oceania', flag: '🇲🇭', lat: 7.1068, lng: 171.3853, description: 'A sprawling chain of volcanic islands and coral atolls in the central Pacific Ocean.', area: '181', currency: 'United States dollar', languages: ['Marshallese', 'English'], borders: [], gdp: '$280M', timeZone: 'UTC+12', callingCode: '+692', driveSide: 'Right' },
  { id: '109', name: 'Mauritania', capital: 'Nouakchott', population: '4.7M', region: 'Africa', flag: '🇲🇷', lat: 18.0735, lng: -15.9582, description: 'A country in Northwest Africa, bridging the Maghreb and western sub-Saharan Africa.', area: '1.03M', currency: 'Ouguiya', languages: ['Arabic'], borders: ['Western Sahara', 'Algeria', 'Mali', 'Senegal'], gdp: '$10B', timeZone: 'UTC+0', callingCode: '+222', driveSide: 'Right' },
  { id: '110', name: 'Mauritius', capital: 'Port Louis', population: '1.2M', region: 'Africa', flag: '🇲🇺', lat: -20.1609, lng: 57.5015, description: 'An Indian Ocean island nation known for its beaches, lagoons and reefs.', area: '2K', currency: 'Mauritian rupee', languages: ['English', 'French'], borders: [], gdp: '$11B', timeZone: 'UTC+4', callingCode: '+230', driveSide: 'Left' },
  { id: '111', name: 'Mexico', capital: 'Mexico City', population: '127.5M', region: 'North America', flag: '🇲🇽', lat: 19.4326, lng: -99.1332, description: 'A country in the southern portion of North America, known for its Pacific and Gulf beaches and diverse landscape.', area: '1.96M', currency: 'Mexican peso', languages: ['Spanish'], borders: ['United States', 'Guatemala', 'Belize'], gdp: '$1.4T', timeZone: 'UTC-5 to -8', callingCode: '+52', driveSide: 'Right' },
  { id: '112', name: 'Micronesia', capital: 'Palikir', population: '114K', region: 'Oceania', flag: '🇫🇲', lat: 6.9248, lng: 158.1611, description: 'The Federated States of Micronesia is a country spread across the western Pacific Ocean comprising more than 600 islands.', area: '702', currency: 'United States dollar', languages: ['English'], borders: [], gdp: '$400M', timeZone: 'UTC+10 to +11', callingCode: '+691', driveSide: 'Right' },
  { id: '113', name: 'Moldova', capital: 'Chișinău', population: '2.5M', region: 'Europe', flag: '🇲🇩', lat: 47.0105, lng: 28.8638, description: 'An Eastern European country and former Soviet republic, known for its vineyards and wine regions.', area: '33.8K', currency: 'Moldovan leu', languages: ['Romanian'], borders: ['Romania', 'Ukraine'], gdp: '$14B', timeZone: 'UTC+2', callingCode: '+373', driveSide: 'Right' },
  { id: '114', name: 'Monaco', capital: 'Monaco', population: '36K', region: 'Europe', flag: '🇲🇨', lat: 43.7384, lng: 7.4246, description: 'A tiny independent city-state on France’s Mediterranean coastline known for its upscale casinos and yacht-lined harbor.', area: '2', currency: 'Euro', languages: ['French'], borders: ['France'], gdp: '$8.7B', timeZone: 'UTC+1', callingCode: '+377', driveSide: 'Right' },
  { id: '115', name: 'Mongolia', capital: 'Ulaanbaatar', population: '3.4M', region: 'Asia', flag: '🇲🇳', lat: 47.9188, lng: 106.9176, description: 'A nation bordered by China and Russia, known for vast, rugged expanses and nomadic culture.', area: '1.56M', currency: 'Tögrög', languages: ['Mongolian'], borders: ['Russia', 'China'], gdp: '$16.8B', timeZone: 'UTC+8', callingCode: '+976', driveSide: 'Right' },
  { id: '116', name: 'Montenegro', capital: 'Podgorica', population: '619K', region: 'Europe', flag: '🇲🇪', lat: 42.4304, lng: 19.2594, description: 'A Balkan country with rugged mountains, medieval villages and a narrow strip of beaches along the Adriatic coastline.', area: '13.8K', currency: 'Euro', languages: ['Montenegrin'], borders: ['Croatia', 'Bosnia and Herzegovina', 'Serbia', 'Kosovo', 'Albania'], gdp: '$6B', timeZone: 'UTC+1', callingCode: '+382', driveSide: 'Right' },
  { id: '117', name: 'Morocco', capital: 'Rabat', population: '37.4M', region: 'Africa', flag: '🇲🇦', lat: 34.0209, lng: -6.8416, description: 'A North African country bordering the Atlantic Ocean and Mediterranean Sea, distinguished by its Berber, Arabian and European influences.', area: '446K', currency: 'Moroccan dirham', languages: ['Arabic', 'Berber'], borders: ['Algeria', 'Western Sahara', 'Spain'], gdp: '$134B', timeZone: 'UTC+1', callingCode: '+212', driveSide: 'Right' },
  { id: '118', name: 'Mozambique', capital: 'Maputo', population: '32.9M', region: 'Africa', flag: '🇲🇿', lat: -25.9692, lng: 32.5732, description: 'A southern African nation whose long Indian Ocean coastline is dotted with popular beaches and marine parks.', area: '801K', currency: 'Metical', languages: ['Portuguese'], borders: ['Tanzania', 'Malawi', 'Zambia', 'Zimbabwe', 'Eswatini', 'South Africa'], gdp: '$17B', timeZone: 'UTC+2', callingCode: '+258', driveSide: 'Left' },
  { id: '119', name: 'Myanmar', capital: 'Naypyidaw', population: '54.1M', region: 'Asia', flag: '🇲🇲', lat: 19.7633, lng: 96.0785, description: 'Also known as Burma, a Southeast Asian nation of more than 100 ethnic groups, bordering India, Bangladesh, China, Laos and Thailand.', area: '676K', currency: 'Kyat', languages: ['Burmese'], borders: ['Bangladesh', 'India', 'China', 'Laos', 'Thailand'], gdp: '$65B', timeZone: 'UTC+6:30', callingCode: '+95', driveSide: 'Right' },

  // --- N ---
  { id: '120', name: 'Namibia', capital: 'Windhoek', population: '2.5M', region: 'Africa', flag: '🇳🇦', lat: -22.5609, lng: 17.0658, description: 'A country in southwest Africa, distinguished by the Namib Desert along its Atlantic Ocean coast.', area: '825K', currency: 'Namibian dollar', languages: ['English'], borders: ['Angola', 'Zambia', 'Botswana', 'South Africa'], gdp: '$12B', timeZone: 'UTC+2', callingCode: '+264', driveSide: 'Left' },
  { id: '121', name: 'Nauru', capital: 'Yaren', population: '12K', region: 'Oceania', flag: '🇳🇷', lat: -0.5477, lng: 166.9209, description: 'A tiny island country in Micronesia, northeast of Australia, featuring a coral reef and white-sand beaches.', area: '21', currency: 'Australian dollar', languages: ['Nauruan', 'English'], borders: [], gdp: '$150M', timeZone: 'UTC+12', callingCode: '+674', driveSide: 'Left' },
  { id: '122', name: 'Nepal', capital: 'Kathmandu', population: '30.5M', region: 'Asia', flag: '🇳🇵', lat: 27.7172, lng: 85.3240, description: 'A landlocked country in South Asia, mainly situated in the Himalayas, including Mount Everest.', area: '147K', currency: 'Nepalese rupee', languages: ['Nepali'], borders: ['China', 'India'], gdp: '$40B', timeZone: 'UTC+5:45', callingCode: '+977', driveSide: 'Left' },
  { id: '123', name: 'Netherlands', capital: 'Amsterdam', population: '17.7M', region: 'Europe', flag: '🇳🇱', lat: 52.3676, lng: 4.9041, description: 'A country in northwestern Europe, known for a flat landscape of canals, tulip fields, windmills and cycling routes.', area: '41.5K', currency: 'Euro', languages: ['Dutch'], borders: ['Germany', 'Belgium'], gdp: '$1T', timeZone: 'UTC+1', callingCode: '+31', driveSide: 'Right' },
  { id: '124', name: 'New Zealand', capital: 'Wellington', population: '5.1M', region: 'Oceania', flag: '🇳🇿', lat: -41.2865, lng: 174.7762, description: 'An island country in the southwestern Pacific Ocean, comprising two main landmasses and numerous smaller islands.', area: '268K', currency: 'New Zealand dollar', languages: ['English', 'Māori'], borders: [], gdp: '$247B', timeZone: 'UTC+12', callingCode: '+64', driveSide: 'Left' },
  { id: '125', name: 'Nicaragua', capital: 'Managua', population: '6.8M', region: 'North America', flag: '🇳🇮', lat: 12.1150, lng: -86.2362, description: 'Set between the Pacific Ocean and the Caribbean Sea, known for its dramatic terrain of lakes, volcanoes and beaches.', area: '130K', currency: 'Córdoba', languages: ['Spanish'], borders: ['Honduras', 'Costa Rica'], gdp: '$15B', timeZone: 'UTC-6', callingCode: '+505', driveSide: 'Right' },
  { id: '126', name: 'Niger', capital: 'Niamey', population: '26.2M', region: 'Africa', flag: '🇳🇪', lat: 13.5116, lng: 2.1254, description: 'A landlocked country in West Africa, named after the Niger River.', area: '1.27M', currency: 'West African CFA franc', languages: ['French'], borders: ['Libya', 'Chad', 'Nigeria', 'Benin', 'Burkina Faso', 'Mali', 'Algeria'], gdp: '$14B', timeZone: 'UTC+1', callingCode: '+227', driveSide: 'Right' },
  { id: '127', name: 'Nigeria', capital: 'Abuja', population: '218M', region: 'Africa', flag: '🇳🇬', lat: 9.0765, lng: 7.3986, description: 'An African country on the Gulf of Guinea, known for its natural landmarks and wildlife reserves.', area: '923K', currency: 'Naira', languages: ['English'], borders: ['Niger', 'Chad', 'Cameroon', 'Benin'], gdp: '$477B', timeZone: 'UTC+1', callingCode: '+234', driveSide: 'Right' },
  { id: '128', name: 'North Korea', capital: 'Pyongyang', population: '26M', region: 'Asia', flag: '🇰🇵', lat: 39.0392, lng: 125.7625, description: 'A country in East Asia constituting the northern part of the Korean Peninsula.', area: '120K', currency: 'North Korean won', languages: ['Korean'], borders: ['China', 'Russia', 'South Korea'], gdp: '$16B', timeZone: 'UTC+9', callingCode: '+850', driveSide: 'Right' },
  { id: '129', name: 'North Macedonia', capital: 'Skopje', population: '2M', region: 'Europe', flag: '🇲🇰', lat: 41.9981, lng: 21.4254, description: 'A landlocked country in the Balkan Peninsula in Southeast Europe.', area: '25.7K', currency: 'Macedonian denar', languages: ['Macedonian'], borders: ['Serbia', 'Bulgaria', 'Greece', 'Albania', 'Kosovo'], gdp: '$13B', timeZone: 'UTC+1', callingCode: '+389', driveSide: 'Right' },
  { id: '130', name: 'Norway', capital: 'Oslo', population: '5.4M', region: 'Europe', flag: '🇳🇴', lat: 59.9139, lng: 10.7522, description: 'A Scandinavian country encompassing mountains, glaciers and deep coastal fjords.', area: '385K', currency: 'Norwegian krone', languages: ['Norwegian'], borders: ['Sweden', 'Finland', 'Russia'], gdp: '$579B', timeZone: 'UTC+1', callingCode: '+47', driveSide: 'Right' },
  
  // --- O ---
  { id: '131', name: 'Oman', capital: 'Muscat', population: '4.5M', region: 'Asia', flag: '🇴🇲', lat: 23.5859, lng: 58.4059, description: 'An Arabian country on the southeastern coast of the Arabian Peninsula, featuring deserts, riverbed oases and long coastlines.', area: '309K', currency: 'Omani rial', languages: ['Arabic'], borders: ['Saudi Arabia', 'UAE', 'Yemen'], gdp: '$114B', timeZone: 'UTC+4', callingCode: '+968', driveSide: 'Right' },
  
  // --- P ---
  { id: '132', name: 'Pakistan', capital: 'Islamabad', population: '235M', region: 'Asia', flag: '🇵🇰', lat: 33.6844, lng: 73.0479, description: 'A country in South Asia, featuring diverse landscapes from the Arabian Sea to the peaks of the Karakoram and Himalayas.', area: '881K', currency: 'Pakistani rupee', languages: ['Urdu', 'English'], borders: ['Iran', 'Afghanistan', 'China', 'India'], gdp: '$376B', timeZone: 'UTC+5', callingCode: '+92', driveSide: 'Left' },
  { id: '133', name: 'Palau', capital: 'Ngerulmud', population: '18K', region: 'Oceania', flag: '🇵🇼', lat: 7.5006, lng: 134.6242, description: 'An archipelago of over 500 islands, part of the Micronesia region in the western Pacific Ocean.', area: '459', currency: 'United States dollar', languages: ['Palauan', 'English'], borders: [], gdp: '$250M', timeZone: 'UTC+9', callingCode: '+680', driveSide: 'Right' },
  { id: '134', name: 'Palestine', capital: 'Ramallah', population: '5.3M', region: 'Asia', flag: '🇵🇸', lat: 31.9038, lng: 35.2034, description: 'A state located in the Southern Levant, generally recognized to comprise the West Bank and Gaza Strip.', area: '6K', currency: 'New Shekel', languages: ['Arabic'], borders: ['Israel', 'Jordan', 'Egypt'], gdp: '$18B', timeZone: 'UTC+2', callingCode: '+970', driveSide: 'Right' },
  { id: '135', name: 'Panama', capital: 'Panama City', population: '4.4M', region: 'North America', flag: '🇵🇦', lat: 8.9824, lng: -79.5199, description: 'A country on the isthmus linking Central and South America. The Panama Canal cuts through its center.', area: '75.4K', currency: 'Balboa', languages: ['Spanish'], borders: ['Costa Rica', 'Colombia'], gdp: '$76B', timeZone: 'UTC-5', callingCode: '+507', driveSide: 'Right' },
  { id: '136', name: 'Papua New Guinea', capital: 'Port Moresby', population: '10.1M', region: 'Oceania', flag: '🇵🇬', lat: -9.4438, lng: 147.1803, description: 'A country in the southwestern Pacific, encompasses the eastern half of New Guinea and its offshore islands.', area: '462K', currency: 'Kina', languages: ['English', 'Tok Pisin', 'Hiri Motu'], borders: ['Indonesia'], gdp: '$31B', timeZone: 'UTC+10', callingCode: '+675', driveSide: 'Left' },
  { id: '137', name: 'Paraguay', capital: 'Asunción', population: '6.7M', region: 'South America', flag: '🇵🇾', lat: -25.2637, lng: -57.5759, description: 'A landlocked country between Argentina, Brazil and Bolivia, home to large swaths of swampland and scrub forest.', area: '406K', currency: 'Guaraní', languages: ['Spanish', 'Guaraní'], borders: ['Argentina', 'Brazil', 'Bolivia'], gdp: '$41B', timeZone: 'UTC-4', callingCode: '+595', driveSide: 'Right' },
  { id: '138', name: 'Peru', capital: 'Lima', population: '34M', region: 'South America', flag: '🇵🇪', lat: -12.0464, lng: -77.0428, description: 'A country in western South America, home to a section of Amazon rainforest and Machu Picchu.', area: '1.28M', currency: 'Sol', languages: ['Spanish'], borders: ['Ecuador', 'Colombia', 'Brazil', 'Bolivia', 'Chile'], gdp: '$242B', timeZone: 'UTC-5', callingCode: '+51', driveSide: 'Right' },
  { id: '139', name: 'Philippines', capital: 'Manila', population: '115M', region: 'Asia', flag: '🇵🇭', lat: 14.5995, lng: 120.9842, description: 'An archipelagic country in Southeast Asia, situated in the western Pacific Ocean.', area: '300K', currency: 'Philippine peso', languages: ['Filipino', 'English'], borders: [], gdp: '$404B', timeZone: 'UTC+8', callingCode: '+63', driveSide: 'Right' },
  { id: '140', name: 'Poland', capital: 'Warsaw', population: '36.8M', region: 'Europe', flag: '🇵🇱', lat: 52.2297, lng: 21.0122, description: 'A country in Central Europe, known for its medieval architecture and Jewish heritage.', area: '312K', currency: 'Złoty', languages: ['Polish'], borders: ['Germany', 'Czechia', 'Slovakia', 'Ukraine', 'Belarus', 'Lithuania', 'Russia'], gdp: '$688B', timeZone: 'UTC+1', callingCode: '+48', driveSide: 'Right' },
  { id: '141', name: 'Portugal', capital: 'Lisbon', population: '10.4M', region: 'Europe', flag: '🇵🇹', lat: 38.7223, lng: -9.1393, description: 'A southern European country on the Iberian Peninsula, bordering Spain.', area: '92K', currency: 'Euro', languages: ['Portuguese'], borders: ['Spain'], gdp: '$251B', timeZone: 'UTC+0', callingCode: '+351', driveSide: 'Right' },
  
  // --- Q ---
  { id: '142', name: 'Qatar', capital: 'Doha', population: '2.7M', region: 'Asia', flag: '🇶🇦', lat: 25.2854, lng: 51.5310, description: 'A peninsular Arab country whose terrain comprises arid desert and a long Persian Gulf shoreline.', area: '11.5K', currency: 'Qatari riyal', languages: ['Arabic'], borders: ['Saudi Arabia'], gdp: '$237B', timeZone: 'UTC+3', callingCode: '+974', driveSide: 'Right' },
  
  // --- R ---
  { id: '143', name: 'Romania', capital: 'Bucharest', population: '19M', region: 'Europe', flag: '🇷🇴', lat: 44.4268, lng: 26.1025, description: 'A southeastern European country known for the forested region of Transylvania, ringed by the Carpathian Mountains.', area: '238K', currency: 'Romanian leu', languages: ['Romanian'], borders: ['Bulgaria', 'Serbia', 'Hungary', 'Ukraine', 'Moldova'], gdp: '$301B', timeZone: 'UTC+2', callingCode: '+40', driveSide: 'Right' },
  { id: '144', name: 'Russia', capital: 'Moscow', population: '144M', region: 'Europe', flag: '🇷🇺', lat: 55.7558, lng: 37.6173, description: 'The largest country in the world, extending across Eastern Europe and Northern Asia.', area: '17.1M', currency: 'Russian ruble', languages: ['Russian'], borders: ['Norway', 'Finland', 'Estonia', 'Latvia', 'Lithuania', 'Poland', 'Belarus', 'Ukraine', 'Georgia', 'Azerbaijan', 'Kazakhstan', 'China', 'Mongolia', 'North Korea'], gdp: '$2.2T', timeZone: 'UTC+2 to +12', callingCode: '+7', driveSide: 'Right' },
  { id: '145', name: 'Rwanda', capital: 'Kigali', population: '13.7M', region: 'Africa', flag: '🇷🇼', lat: -1.9441, lng: 30.0619, description: 'A landlocked East African country with a green, mountainous landscape, home to mountain gorillas.', area: '26.3K', currency: 'Rwandan franc', languages: ['Kinyarwanda', 'French', 'English'], borders: ['Uganda', 'Tanzania', 'Burundi', 'DR Congo'], gdp: '$13B', timeZone: 'UTC+2', callingCode: '+250', driveSide: 'Right' },
  
  // --- S ---
  { id: '146', name: 'Saint Kitts and Nevis', capital: 'Basseterre', population: '47K', region: 'North America', flag: '🇰🇳', lat: 17.3026, lng: -62.7177, description: 'A dual-island nation situated between the Atlantic Ocean and Caribbean Sea.', area: '261', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$1B', timeZone: 'UTC-4', callingCode: '+1-869', driveSide: 'Left' },
  { id: '147', name: 'Saint Lucia', capital: 'Castries', population: '179K', region: 'North America', flag: '🇱🇨', lat: 14.0101, lng: -60.9875, description: 'An Eastern Caribbean island nation with a pair of dramatically tapered mountains, the Pitons, on its west coast.', area: '616', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$2.3B', timeZone: 'UTC-4', callingCode: '+1-758', driveSide: 'Left' },
  { id: '148', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown', population: '103K', region: 'North America', flag: '🇻🇨', lat: 13.1600, lng: -61.2248, description: 'A southern Caribbean nation comprising a main island, St. Vincent, and a chain of smaller islands.', area: '389', currency: 'East Caribbean dollar', languages: ['English'], borders: [], gdp: '$0.9B', timeZone: 'UTC-4', callingCode: '+1-784', driveSide: 'Left' },
  { id: '149', name: 'Samoa', capital: 'Apia', population: '222K', region: 'Oceania', flag: '🇼🇸', lat: -13.8333, lng: -171.7667, description: 'A country comprising the western group of the Samoan Islands in Polynesia.', area: '2.8K', currency: 'Tala', languages: ['Samoan', 'English'], borders: [], gdp: '$850M', timeZone: 'UTC+13', callingCode: '+685', driveSide: 'Left' },
  { id: '150', name: 'San Marino', capital: 'San Marino', population: '33K', region: 'Europe', flag: '🇸🇲', lat: 43.9346, lng: 12.4473, description: 'A mountainous microstate surrounded by north-central Italy, one of the world\'s oldest republics.', area: '61', currency: 'Euro', languages: ['Italian'], borders: ['Italy'], gdp: '$1.7B', timeZone: 'UTC+1', callingCode: '+378', driveSide: 'Right' },
  { id: '151', name: 'São Tomé and Príncipe', capital: 'São Tomé', population: '227K', region: 'Africa', flag: '🇸🇹', lat: 0.3302, lng: 6.7333, description: 'An African island nation close to the equator, known for its coral formations and rainforests.', area: '964', currency: 'Dobra', languages: ['Portuguese'], borders: [], gdp: '$0.5B', timeZone: 'UTC+0', callingCode: '+239', driveSide: 'Right' },
  { id: '152', name: 'Saudi Arabia', capital: 'Riyadh', population: '36.4M', region: 'Asia', flag: '🇸🇦', lat: 24.7136, lng: 46.6753, description: 'A desert country encompassing most of the Arabian Peninsula, with Red Sea and Persian Gulf coastlines.', area: '2.15M', currency: 'Saudi riyal', languages: ['Arabic'], borders: ['Jordan', 'Iraq', 'Kuwait', 'Qatar', 'UAE', 'Oman', 'Yemen'], gdp: '$1.1T', timeZone: 'UTC+3', callingCode: '+966', driveSide: 'Right' },
  { id: '153', name: 'Senegal', capital: 'Dakar', population: '17.3M', region: 'Africa', flag: '🇸🇳', lat: 14.7167, lng: -17.4677, description: 'A country on Africa’s west coast with a rich French colonial heritage and many natural attractions.', area: '196K', currency: 'West African CFA franc', languages: ['French', 'Wolof'], borders: ['Mauritania', 'Mali', 'Guinea', 'Guinea-Bissau', 'Gambia'], gdp: '$27B', timeZone: 'UTC+0', callingCode: '+221', driveSide: 'Right' },
  { id: '154', name: 'Serbia', capital: 'Belgrade', population: '6.6M', region: 'Europe', flag: '🇷🇸', lat: 44.7866, lng: 20.4489, description: 'A landlocked country in the Balkans, known for its mountains and ski resorts.', area: '88.3K', currency: 'Serbian dinar', languages: ['Serbian'], borders: ['Hungary', 'Romania', 'Bulgaria', 'North Macedonia', 'Kosovo', 'Montenegro', 'Bosnia and Herzegovina', 'Croatia'], gdp: '$63B', timeZone: 'UTC+1', callingCode: '+381', driveSide: 'Right' },
  { id: '155', name: 'Seychelles', capital: 'Victoria', population: '119K', region: 'Africa', flag: '🇸🇨', lat: -4.6191, lng: 55.4513, description: 'An archipelago of 115 islands in the Indian Ocean, off East Africa, known for its beaches and coral reefs.', area: '459', currency: 'Seychellois rupee', languages: ['Seychellois Creole', 'English', 'French'], borders: [], gdp: '$1.5B', timeZone: 'UTC+4', callingCode: '+248', driveSide: 'Left' },
  { id: '156', name: 'Sierra Leone', capital: 'Freetown', population: '8.6M', region: 'Africa', flag: '🇸🇱', lat: 8.4657, lng: -13.2317, description: 'A country in West Africa, known for the white-sand beaches on the Freetown Peninsula.', area: '71.7K', currency: 'Leone', languages: ['English'], borders: ['Guinea', 'Liberia'], gdp: '$4B', timeZone: 'UTC+0', callingCode: '+232', driveSide: 'Right' },
  { id: '157', name: 'Singapore', capital: 'Singapore', population: '5.6M', region: 'Asia', flag: '🇸🇬', lat: 1.3521, lng: 103.8198, description: 'A sovereign island city-state in maritime Southeast Asia.', area: '728', currency: 'Singapore dollar', languages: ['English', 'Malay', 'Mandarin', 'Tamil'], borders: ['Malaysia'], gdp: '$466B', timeZone: 'UTC+8', callingCode: '+65', driveSide: 'Left' },
  { id: '158', name: 'Slovakia', capital: 'Bratislava', population: '5.4M', region: 'Europe', flag: '🇸🇰', lat: 48.1486, lng: 17.1077, description: 'A landlocked country in Central Europe, known for its dramatic natural landscape and many castles.', area: '49K', currency: 'Euro', languages: ['Slovak'], borders: ['Poland', 'Ukraine', 'Hungary', 'Austria', 'Czechia'], gdp: '$115B', timeZone: 'UTC+1', callingCode: '+421', driveSide: 'Right' },
  { id: '159', name: 'Slovenia', capital: 'Ljubljana', population: '2.1M', region: 'Europe', flag: '🇸🇮', lat: 46.0569, lng: 14.5058, description: 'A country in Central Europe known for its mountains, ski resorts and lakes.', area: '20.2K', currency: 'Euro', languages: ['Slovene'], borders: ['Austria', 'Hungary', 'Croatia', 'Italy'], gdp: '$68B', timeZone: 'UTC+1', callingCode: '+386', driveSide: 'Right' },
  { id: '160', name: 'Solomon Islands', capital: 'Honiara', population: '724K', region: 'Oceania', flag: '🇸🇧', lat: -9.4456, lng: 159.9729, description: 'A nation of hundreds of islands in the South Pacific, featuring WWII sites.', area: '28.8K', currency: 'Solomon Islands dollar', languages: ['English'], borders: [], gdp: '$1.6B', timeZone: 'UTC+11', callingCode: '+677', driveSide: 'Left' },
  { id: '161', name: 'Somalia', capital: 'Mogadishu', population: '17M', region: 'Africa', flag: '🇸🇴', lat: 2.0469, lng: 45.3182, description: 'A country in the Horn of Africa, with the longest coastline on Africa\'s mainland.', area: '637K', currency: 'Somali shilling', languages: ['Somali', 'Arabic'], borders: ['Djibouti', 'Ethiopia', 'Kenya'], gdp: '$8B', timeZone: 'UTC+3', callingCode: '+252', driveSide: 'Right' },
  { id: '162', name: 'South Africa', capital: 'Pretoria', population: '59.9M', region: 'Africa', flag: '🇿🇦', lat: -25.7479, lng: 28.2293, description: 'A country on the southernmost tip of the African continent, marked by several distinct ecosystems.', area: '1.22M', currency: 'South African rand', languages: ['Zulu', 'Xhosa', 'Afrikaans', 'English'], borders: ['Namibia', 'Botswana', 'Zimbabwe', 'Mozambique', 'Eswatini', 'Lesotho'], gdp: '$405B', timeZone: 'UTC+2', callingCode: '+27', driveSide: 'Left' },
  { id: '163', name: 'South Korea', capital: 'Seoul', population: '51.6M', region: 'Asia', flag: '🇰🇷', lat: 37.5665, lng: 126.9780, description: 'An East Asian nation on the southern half of the Korean Peninsula, known for its green, hilly countryside and high-tech cities.', area: '100K', currency: 'South Korean won', languages: ['Korean'], borders: ['North Korea'], gdp: '$1.7T', timeZone: 'UTC+9', callingCode: '+82', driveSide: 'Right' },
  { id: '164', name: 'South Sudan', capital: 'Juba', population: '10.9M', region: 'Africa', flag: '🇸🇸', lat: 4.8594, lng: 31.5713, description: 'A landlocked country in East Africa, gaining independence from Sudan in 2011.', area: '619K', currency: 'South Sudanese pound', languages: ['English'], borders: ['Sudan', 'Ethiopia', 'Kenya', 'Uganda', 'DR Congo', 'Central African Republic'], gdp: '$12B', timeZone: 'UTC+2', callingCode: '+211', driveSide: 'Right' },
  { id: '165', name: 'Spain', capital: 'Madrid', population: '47.6M', region: 'Europe', flag: '🇪🇸', lat: 40.4168, lng: -3.7038, description: 'A vibrant European nation on the Iberian Peninsula, famous for its art history, diverse regional cultures, and Mediterranean coastline.', area: '505K', currency: 'Euro', languages: ['Spanish'], borders: ['France', 'Portugal', 'Andorra', 'Morocco', 'Gibraltar'], gdp: '$1.4T', timeZone: 'UTC+1', callingCode: '+34', driveSide: 'Right' },
  { id: '166', name: 'Sri Lanka', capital: 'Colombo', population: '22.1M', region: 'Asia', flag: '🇱🇰', lat: 6.9271, lng: 79.8612, description: 'An island country in South Asia, located in the Indian Ocean southwest of the Bay of Bengal.', area: '65.6K', currency: 'Sri Lankan rupee', languages: ['Sinhala', 'Tamil'], borders: [], gdp: '$74B', timeZone: 'UTC+5:30', callingCode: '+94', driveSide: 'Left' },
  { id: '167', name: 'Sudan', capital: 'Khartoum', population: '46.8M', region: 'Africa', flag: '🇸🇩', lat: 15.5007, lng: 32.5599, description: 'A country in Northeast Africa, crossed by the Nile River and home to ancient pyramids.', area: '1.86M', currency: 'Sudanese pound', languages: ['Arabic', 'English'], borders: ['Egypt', 'Eritrea', 'Ethiopia', 'South Sudan', 'Central African Republic', 'Chad', 'Libya'], gdp: '$51B', timeZone: 'UTC+2', callingCode: '+249', driveSide: 'Right' },
  { id: '168', name: 'Suriname', capital: 'Paramaribo', population: '618K', region: 'South America', flag: '🇸🇷', lat: 5.8520, lng: -55.2038, description: 'A small country on the northeastern coast of South America, defined by vast swaths of tropical rainforest.', area: '163K', currency: 'Surinamese dollar', languages: ['Dutch'], borders: ['French Guiana', 'Guyana', 'Brazil'], gdp: '$3.6B', timeZone: 'UTC-3', callingCode: '+597', driveSide: 'Left' },
  { id: '169', name: 'Sweden', capital: 'Stockholm', population: '10.5M', region: 'Europe', flag: '🇸🇪', lat: 59.3293, lng: 18.0686, description: 'A Scandinavian nation with thousands of coastal islands and inland lakes, along with vast boreal forests.', area: '450K', currency: 'Swedish krona', languages: ['Swedish'], borders: ['Norway', 'Finland'], gdp: '$591B', timeZone: 'UTC+1', callingCode: '+46', driveSide: 'Right' },
  { id: '170', name: 'Switzerland', capital: 'Bern', population: '8.7M', region: 'Europe', flag: '🇨🇭', lat: 46.9480, lng: 7.4474, description: 'A mountainous Central European country, home to numerous lakes, villages and the high peaks of the Alps.', area: '41.2K', currency: 'Swiss franc', languages: ['German', 'French', 'Italian'], borders: ['Germany', 'France', 'Italy', 'Austria', 'Liechtenstein'], gdp: '$807B', timeZone: 'UTC+1', callingCode: '+41', driveSide: 'Right' },
  { id: '171', name: 'Syria', capital: 'Damascus', population: '22.1M', region: 'Asia', flag: '🇸🇾', lat: 33.5138, lng: 36.2765, description: 'A country in Western Asia, bordering the Mediterranean Sea and home to some of the oldest cities in the world.', area: '185K', currency: 'Syrian pound', languages: ['Arabic'], borders: ['Turkey', 'Iraq', 'Jordan', 'Israel', 'Lebanon'], gdp: '$11B', timeZone: 'UTC+3', callingCode: '+963', driveSide: 'Right' },
  
  // --- T ---
  { id: '172', name: 'Tajikistan', capital: 'Dushanbe', population: '9.9M', region: 'Asia', flag: '🇹🇯', lat: 38.5598, lng: 68.7870, description: 'A mountainous landlocked country in Central Asia, dominated by the majestic Pamir and Fann mountain ranges.', area: '143K', currency: 'Somoni', languages: ['Tajik'], borders: ['Afghanistan', 'China', 'Kyrgyzstan', 'Uzbekistan'], gdp: '$10B', timeZone: 'UTC+5', callingCode: '+992', driveSide: 'Right' },
  { id: '173', name: 'Tanzania', capital: 'Dodoma', population: '65.4M', region: 'Africa', flag: '🇹🇿', lat: -6.1630, lng: 35.7516, description: 'An East African country known for its vast wilderness areas, including the plains of Serengeti National Park.', area: '945K', currency: 'Tanzanian shilling', languages: ['Swahili', 'English'], borders: ['Kenya', 'Uganda', 'Rwanda', 'Burundi', 'DR Congo', 'Zambia', 'Malawi', 'Mozambique'], gdp: '$76B', timeZone: 'UTC+3', callingCode: '+255', driveSide: 'Left' },
  { id: '174', name: 'Thailand', capital: 'Bangkok', population: '71.7M', region: 'Asia', flag: '🇹🇭', lat: 13.7563, lng: 100.5018, description: 'A Southeast Asian country known for its tropical beaches, opulent royal palaces, ancient ruins, and ornate temples.', area: '513K', currency: 'Baht', languages: ['Thai'], borders: ['Myanmar', 'Laos', 'Cambodia', 'Malaysia'], gdp: '$495B', timeZone: 'UTC+7', callingCode: '+66', driveSide: 'Left' },
  { id: '51', name: 'Timor-Leste', capital: 'Dili', population: '1.3M', region: 'Asia', flag: '🇹🇱', lat: -8.5569, lng: 125.5603, description: 'A Southeast Asian nation occupying half the island of Timor, ringed by coral reefs teeming with marine life.', area: '15K', currency: 'United States dollar', languages: ['Tetum', 'Portuguese'], borders: ['Indonesia'], gdp: '$2.5B', timeZone: 'UTC+9', callingCode: '+670', driveSide: 'Left' },
  { id: '175', name: 'Togo', capital: 'Lomé', population: '8.8M', region: 'Africa', flag: '🇹🇬', lat: 6.1375, lng: 1.2125, description: 'A West African nation on the Gulf of Guinea, known for its palm-lined beaches and hilltop villages.', area: '56.7K', currency: 'West African CFA franc', languages: ['French'], borders: ['Ghana', 'Benin', 'Burkina Faso'], gdp: '$8B', timeZone: 'UTC+0', callingCode: '+228', driveSide: 'Right' },
  { id: '176', name: 'Tonga', capital: 'Nuku\'alofa', population: '106K', region: 'Oceania', flag: '🇹🇴', lat: -21.1393, lng: -175.2049, description: 'A Polynesian kingdom of more than 170 South Pacific islands, many uninhabited, most lined in white beaches.', area: '747', currency: 'Pa\'anga', languages: ['Tongan', 'English'], borders: [], gdp: '$500M', timeZone: 'UTC+13', callingCode: '+676', driveSide: 'Left' },
  { id: '177', name: 'Trinidad and Tobago', capital: 'Port of Spain', population: '1.5M', region: 'North America', flag: '🇹🇹', lat: 10.6549, lng: -61.5022, description: 'A dual-island Caribbean nation near Venezuela, with distinctive Creole traditions and cuisines.', area: '5.1K', currency: 'Trinidad and Tobago dollar', languages: ['English'], borders: [], gdp: '$28B', timeZone: 'UTC-4', callingCode: '+1-868', driveSide: 'Left' },
  { id: '178', name: 'Tunisia', capital: 'Tunis', population: '12.3M', region: 'Africa', flag: '🇹🇳', lat: 36.8065, lng: 10.1815, description: 'A North African country bordering the Mediterranean Sea and Sahara Desert, home to the ancient city of Carthage.', area: '163K', currency: 'Tunisian dinar', languages: ['Arabic'], borders: ['Algeria', 'Libya'], gdp: '$46B', timeZone: 'UTC+1', callingCode: '+216', driveSide: 'Right' },
  { id: '179', name: 'Turkey', capital: 'Ankara', population: '85.3M', region: 'Asia', flag: '🇹🇷', lat: 39.9334, lng: 32.8597, description: 'A transcontinental country located mainly on the Anatolian Peninsula in Western Asia, with a small portion on the Balkan Peninsula.', area: '783K', currency: 'Turkish lira', languages: ['Turkish'], borders: ['Greece', 'Bulgaria', 'Georgia', 'Armenia', 'Azerbaijan', 'Iran', 'Iraq', 'Syria'], gdp: '$906B', timeZone: 'UTC+3', callingCode: '+90', driveSide: 'Right' },
  { id: '180', name: 'Turkmenistan', capital: 'Ashgabat', population: '6.4M', region: 'Asia', flag: '🇹🇲', lat: 37.9601, lng: 58.3261, description: 'A Central Asian nation known for its vast Karakum Desert and ancient Silk Road ruins.', area: '488K', currency: 'Turkmenistan manat', languages: ['Turkmen'], borders: ['Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iran'], gdp: '$45B', timeZone: 'UTC+5', callingCode: '+993', driveSide: 'Right' },
  { id: '181', name: 'Tuvalu', capital: 'Funafuti', population: '11K', region: 'Oceania', flag: '🇹🇻', lat: -8.5200, lng: 179.1960, description: 'An independent island nation in the South Pacific, comprising nine small islands.', area: '26', currency: 'Tuvaluan dollar', languages: ['Tuvaluan', 'English'], borders: [], gdp: '$60M', timeZone: 'UTC+12', callingCode: '+688', driveSide: 'Left' },
  
  // --- U ---
  { id: '182', name: 'Uganda', capital: 'Kampala', population: '47.2M', region: 'Africa', flag: '🇺🇬', lat: 0.3476, lng: 32.5825, description: 'A landlocked country in East Africa whose diverse landscape encompasses the snow-capped Rwenzori Mountains and immense Lake Victoria.', area: '241K', currency: 'Ugandan shilling', languages: ['English', 'Swahili'], borders: ['South Sudan', 'Kenya', 'Tanzania', 'Rwanda', 'DR Congo'], gdp: '$45B', timeZone: 'UTC+3', callingCode: '+256', driveSide: 'Left' },
  { id: '183', name: 'Ukraine', capital: 'Kyiv', population: '41M', region: 'Europe', flag: '🇺🇦', lat: 50.4501, lng: 30.5234, description: 'A large country in Eastern Europe known for its Orthodox churches, Black Sea coastline and forested mountains.', area: '603K', currency: 'Hryvnia', languages: ['Ukrainian'], borders: ['Russia', 'Belarus', 'Poland', 'Slovakia', 'Hungary', 'Romania', 'Moldova'], gdp: '$160B', timeZone: 'UTC+2', callingCode: '+380', driveSide: 'Right' },
  { id: '184', name: 'United Arab Emirates', capital: 'Abu Dhabi', population: '9.4M', region: 'Asia', flag: '🇦🇪', lat: 24.4539, lng: 54.3773, description: 'A country on the Arabian Peninsula settled mainly along the Persian Gulf, a federation of 7 emirates.', area: '83.6K', currency: 'UAE dirham', languages: ['Arabic'], borders: ['Saudi Arabia', 'Oman'], gdp: '$507B', timeZone: 'UTC+4', callingCode: '+971', driveSide: 'Right' },
  { id: '185', name: 'United Kingdom', capital: 'London', population: '67.5M', region: 'Europe', flag: '🇬🇧', lat: 51.5074, lng: -0.1278, description: 'An island nation in northwestern Europe comprising England, Scotland, Wales, and Northern Ireland.', area: '242K', currency: 'Pound sterling', languages: ['English'], borders: ['Ireland'], gdp: '$3.1T', timeZone: 'UTC+0', callingCode: '+44', driveSide: 'Left' },
  { id: '186', name: 'United States', capital: 'Washington, D.C.', population: '333.3M', region: 'North America', flag: '🇺🇸', lat: 38.9072, lng: -77.0369, description: 'A federal republic of 50 states spanning North America, known for its cultural impact and diverse geography.', area: '9.83M', currency: 'United States dollar', languages: ['English'], borders: ['Canada', 'Mexico'], gdp: '$25.5T', timeZone: 'UTC-5 to -10', callingCode: '+1', driveSide: 'Right' },
  { id: '187', name: 'Uruguay', capital: 'Montevideo', population: '3.4M', region: 'South America', flag: '🇺🇾', lat: -34.9011, lng: -56.1645, description: 'A South American country known for its verdant interior and beach-lined coast.', area: '176K', currency: 'Uruguayan peso', languages: ['Spanish'], borders: ['Argentina', 'Brazil'], gdp: '$71B', timeZone: 'UTC-3', callingCode: '+598', driveSide: 'Right' },
  { id: '188', name: 'Uzbekistan', capital: 'Tashkent', population: '35.6M', region: 'Asia', flag: '🇺🇿', lat: 41.2995, lng: 69.2401, description: 'A Central Asian nation and former Soviet republic, known for its mosques, mausoleums and sites linked to the Silk Road.', area: '447K', currency: 'Uzbekistani so\'m', languages: ['Uzbek'], borders: ['Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Afghanistan', 'Turkmenistan'], gdp: '$80B', timeZone: 'UTC+5', callingCode: '+998', driveSide: 'Right' },
  
  // --- V ---
  { id: '189', name: 'Vanuatu', capital: 'Port Vila', population: '326K', region: 'Oceania', flag: '🇻🇺', lat: -17.7333, lng: 168.3273, description: 'A South Pacific Ocean nation made up of roughly 80 islands, known for its coral reefs and underwater wrecks.', area: '12.2K', currency: 'Vatu', languages: ['Bislama', 'English', 'French'], borders: [], gdp: '$980M', timeZone: 'UTC+11', callingCode: '+678', driveSide: 'Right' },
  { id: '190', name: 'Vatican City', capital: 'Vatican City', population: '800', region: 'Europe', flag: '🇻🇦', lat: 41.9029, lng: 12.4534, description: 'A city-state surrounded by Rome, Italy, serving as the headquarters of the Roman Catholic Church.', area: '0.44', currency: 'Euro', languages: ['Italian', 'Latin'], borders: ['Italy'], gdp: '$0', timeZone: 'UTC+1', callingCode: '+39', driveSide: 'Right' },
  { id: '191', name: 'Venezuela', capital: 'Caracas', population: '28.3M', region: 'South America', flag: '🇻🇪', lat: 10.4806, lng: -66.9036, description: 'A country on the northern coast of South America with diverse natural attractions, including the Andes and Angel Falls.', area: '916K', currency: 'Bolívar', languages: ['Spanish'], borders: ['Colombia', 'Brazil', 'Guyana'], gdp: '$92B', timeZone: 'UTC-4', callingCode: '+58', driveSide: 'Right' },
  { id: '192', name: 'Vietnam', capital: 'Hanoi', population: '98.1M', region: 'Asia', flag: '🇻🇳', lat: 21.0285, lng: 105.8542, description: 'A Southeast Asian country known for its beaches, rivers, Buddhist pagodas and bustling cities.', area: '331K', currency: 'Dong', languages: ['Vietnamese'], borders: ['China', 'Laos', 'Cambodia'], gdp: '$408B', timeZone: 'UTC+7', callingCode: '+84', driveSide: 'Right' },
  
  // --- Y ---
  { id: '193', name: 'Yemen', capital: 'Sana\'a', population: '33.7M', region: 'Asia', flag: '🇾🇪', lat: 15.3694, lng: 44.1910, description: 'A desert country at the southern tip of the Arabian Peninsula, boasting ancient mud-brick skyscrapers.', area: '527K', currency: 'Yemeni rial', languages: ['Arabic'], borders: ['Saudi Arabia', 'Oman'], gdp: '$21B', timeZone: 'UTC+3', callingCode: '+967', driveSide: 'Right' },
  
  // --- Z ---
  { id: '194', name: 'Zambia', capital: 'Lusaka', population: '20M', region: 'Africa', flag: '🇿🇲', lat: -15.3875, lng: 28.3228, description: 'A landlocked country in Southern Africa, famous for Victoria Falls and walking safaris.', area: '752K', currency: 'Zambian kwacha', languages: ['English'], borders: ['DR Congo', 'Tanzania', 'Malawi', 'Mozambique', 'Zimbabwe', 'Botswana', 'Namibia', 'Angola'], gdp: '$29B', timeZone: 'UTC+2', callingCode: '+260', driveSide: 'Left' },
  { id: '195', name: 'Zimbabwe', capital: 'Harare', population: '16.3M', region: 'Africa', flag: '🇿🇼', lat: -17.8216, lng: 31.0492, description: 'A landlocked country in southern Africa known for its dramatic landscape and diverse wildlife parks.', area: '390K', currency: 'US Dollar', languages: ['English', 'Shona', 'Ndebele'], borders: ['Zambia', 'Mozambique', 'South Africa', 'Botswana'], gdp: '$28B', timeZone: 'UTC+2', callingCode: '+263', driveSide: 'Left' }
];

// Map aliases to the raw data to produce the final export
export const MOCK_COUNTRIES: Country[] = RAW_COUNTRIES.map(country => ({
  ...country,
  alsoKnownAs: COUNTRY_ALIASES[country.id]
}));

export const GAMES: Game[] = [
  { 
    id: '1', 
    title: 'Capital Quiz', 
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/capital-quiz.png', 
    status: 'active', 
    description: 'Test your knowledge against the clock.' 
  },
  { 
    id: '2', 
    title: 'Map Dash', 
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/map-dash.png', 
    status: 'active', 
    description: 'Find the country before time runs out.' 
  },
  { 
    id: '3', 
    title: 'Flag Frenzy', 
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/flag-frenzy.png', 
    status: 'active', 
    description: 'Match the flags to their nations.' 
  },
  {
    id: '4',
    title: 'Know Your Neighbor',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/know-your-neighbor.png', 
    status: 'active', 
    description: 'Identify all the bordering countries.'
  },
  {
    id: '5',
    title: 'Population Pursuit',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/population-pursuit.png',
    status: 'active', 
    description: 'Which country has more people?'
  },
  {
    id: '6',
    title: 'Global Detective',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/global-detective.png', 
    status: 'active', 
    description: 'Deduce the mystery country from 3 clues.'
  },
  {
    id: '7',
    title: 'Capital Connection',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/capital-connection.png',
    status: 'active', 
    description: 'Match countries to their capitals in a race against time.'
  },
  {
    id: '8',
    title: 'Region Roundup',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/region-roundup.png',
    status: 'active', 
    description: 'Sort countries into their correct continents.'
  },
  {
    id: '9',
    title: 'Landmark Legend',
    image: 'https://anaximanderomiletus-byte.github.io/Explore-Capitals-PNGs/0-GAMES/landmark-legend.png',
    status: 'active', 
    description: 'Identify the country from a famous landmark image.'
  }
];
